//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_QUICK_SCREEN
    {
        public string QUICK_SCREEN { get; set; }
        public string TABLE_NAME { get; set; }
        public string QUICK_DESC { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string ACTIVEIND { get; set; }
    }
}
