//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class APP_WH
    {
        public string WAREHOUSE { get; set; }
        public string DESCRIPTION { get; set; }
        public string SYSID { get; set; }
        public string ACTIVEIND { get; set; }
        public string SITE_NAME { get; set; }
        public string WH_ID { get; set; }
        public string DEF_PACK_PRINTER { get; set; }
    
        [JsonIgnore]
        public virtual APP_SITES APP_SITES { get; set; }
        [JsonIgnore]
        public virtual M_SYSTEM M_SYSTEM { get; set; }
        [JsonIgnore]
        public virtual RP_PRINTER RP_PRINTER { get; set; }
    }
}
