//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_DURATION
    {
        public string FROM_SITE_NAME { get; set; }
        public string TO_CITY { get; set; }
        public decimal DAYS { get; set; }
        public Nullable<decimal> DISTANCE { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<byte> KG_FREIGHT { get; set; }
        public string PROVINCE { get; set; }
    
        public virtual APP_SITES APP_SITES { get; set; }
    }
}
