//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_SITES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APP_SITES()
        {
            this.APP_DURATION = new HashSet<APP_DURATION>();
            this.APP_WH = new HashSet<APP_WH>();
            this.RP_PRINTER = new HashSet<RP_PRINTER>();
        }
    
        public string SITE_NAME { get; set; }
        public string SITE_LEADER { get; set; }
        public string LEADER_EMAIL { get; set; }
        public string SITE_PHONE { get; set; }
        public string SITE_ADDR { get; set; }
        public string SITE_CITY { get; set; }
        public string ACTIVEIND { get; set; }
        public string SITE_DESC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_DURATION> APP_DURATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_WH> APP_WH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_PRINTER> RP_PRINTER { get; set; }
    }
}
