//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_WELCOME
    {
        public string WEL_MSG { get; set; }
        public Nullable<decimal> MSG_SEQ { get; set; }
        public string MOBILE_MSG { get; set; }
    }
}
