//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_SPACE_PAGE_LINK
    {
        public string SPACE_CODE { get; set; }
        public string PAGE_NAME { get; set; }
        public string ACTIVEIND { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    
        public virtual APP_PAGES APP_PAGES { get; set; }
        public virtual APP_WORKSPACE APP_WORKSPACE { get; set; }
    }
}
