//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_CUST_ALIAS_LINK
    {
        public string ALIAS_NAME { get; set; }
        public string CUSTOMER_NO { get; set; }
        public decimal BILL_TO_LOCATION { get; set; }
        public decimal SHIP_TO_LOCATION { get; set; }
        public string SYSID { get; set; }
    
        public virtual APP_CUST_ALIAS APP_CUST_ALIAS { get; set; }
        public virtual M_SYSTEM M_SYSTEM { get; set; }
    }
}
