//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_ROLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APP_ROLES()
        {
            this.APP_PAGE_ROLE_LINK = new HashSet<APP_PAGE_ROLE_LINK>();
            this.APP_USER_ROLE_LINK = new HashSet<APP_USER_ROLE_LINK>();
        }
    
        public string ROLE_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string ADMIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_PAGE_ROLE_LINK> APP_PAGE_ROLE_LINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_USER_ROLE_LINK> APP_USER_ROLE_LINK { get; set; }
    }
}
