//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_NOTICE
    {
        public decimal NOTICE_ID { get; set; }
        public string NOTICE_OWNER { get; set; }
        public string NOTICE_EMAIL { get; set; }
        public string NOTICE_TOPIC { get; set; }
        public string NOTICE_TEXT { get; set; }
        public System.DateTime BEGIN_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
    }
}
