//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_WORKSPACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APP_WORKSPACE()
        {
            this.APP_SPACE_PAGE_LINK = new HashSet<APP_SPACE_PAGE_LINK>();
        }
    
        public decimal DISPLAY_SEQ { get; set; }
        public string SPACE_CODE { get; set; }
        public string SPACE_DESC { get; set; }
        public string ACTIVEIND { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_SPACE_PAGE_LINK> APP_SPACE_PAGE_LINK { get; set; }
    }
}
