//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_XCEC_3PL_DAILY_SHIPMENT
    {
        public string CUSTOMER_PO_NO { get; set; }
        public string DEALER_PO_NO { get; set; }
        public long SHIPMENT_NO { get; set; }
        public long SHIPMENT_LINE_NO { get; set; }
        public string CUSTOMER_PARTNO { get; set; }
        public Nullable<decimal> QTY_SHIPPED { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public string CUST_PO_LINE_NO { get; set; }
        public string CUSTOMER_NO { get; set; }
        public string SHIP_TO_ABBR { get; set; }
        public Nullable<int> DEST_LOCATION { get; set; }
        public string CARRIER_CODE { get; set; }
        public string SCAC_DESC { get; set; }
        public string CARRIER_PRO_NO { get; set; }
        public string PACKING_LIST_NO { get; set; }
        public string WAREHOUSE { get; set; }
        public string ORDER_NO { get; set; }
        public string ORDER_TYPE { get; set; }
        public Nullable<long> LINE_NO { get; set; }
        public string PART_NO { get; set; }
        public Nullable<System.DateTime> PICK_LIST_CREATED { get; set; }
        public string CUSTOMER_PO_NOTE { get; set; }
        public string LOCAL_SHIP_TO_NAME { get; set; }
        public string LOCAL_SHIP_TO_ADDR_1 { get; set; }
        public string LOCAL_SHIP_TO_ADDR_2 { get; set; }
        public string LOCAL_SHIP_TO_ADDR_3 { get; set; }
        public string LOCAL_SHIP_TO_CITY { get; set; }
    }
}
