//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHubEntities : DbContext
    {
        public CHubEntities()
            : base("name=CHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_CUST_ALIAS> APP_CUST_ALIAS { get; set; }
        public virtual DbSet<APP_CUST_ALIAS_LINK> APP_CUST_ALIAS_LINK { get; set; }
        public virtual DbSet<APP_DURATION> APP_DURATION { get; set; }
        public virtual DbSet<APP_NOTICE> APP_NOTICE { get; set; }
        public virtual DbSet<APP_ORDER_TYPE> APP_ORDER_TYPE { get; set; }
        public virtual DbSet<APP_PAGE_ROLE_LINK> APP_PAGE_ROLE_LINK { get; set; }
        public virtual DbSet<APP_PAGES> APP_PAGES { get; set; }
        public virtual DbSet<APP_RECENT_PAGES> APP_RECENT_PAGES { get; set; }
        public virtual DbSet<APP_ROLES> APP_ROLES { get; set; }
        public virtual DbSet<APP_SITES> APP_SITES { get; set; }
        public virtual DbSet<APP_SPACE_PAGE_LINK> APP_SPACE_PAGE_LINK { get; set; }
        public virtual DbSet<APP_USER_ALIAS_LINK> APP_USER_ALIAS_LINK { get; set; }
        public virtual DbSet<APP_USER_ROLE_LINK> APP_USER_ROLE_LINK { get; set; }
        public virtual DbSet<APP_USERS> APP_USERS { get; set; }
        public virtual DbSet<APP_WELCOME> APP_WELCOME { get; set; }
        public virtual DbSet<APP_WH> APP_WH { get; set; }
        public virtual DbSet<APP_WORKSPACE> APP_WORKSPACE { get; set; }
        public virtual DbSet<M_PARAMETER> M_PARAMETER { get; set; }
        public virtual DbSet<M_SYSTEM> M_SYSTEM { get; set; }
        public virtual DbSet<TS_ORDER_HEADER> TS_ORDER_HEADER { get; set; }
        public virtual DbSet<TS_ORDER_DETAIL> TS_ORDER_DETAIL { get; set; }
        public virtual DbSet<TS_ORDER_DETAIL_STG> TS_ORDER_DETAIL_STG { get; set; }
        public virtual DbSet<TS_ORDER_HEADER_STG> TS_ORDER_HEADER_STG { get; set; }
        public virtual DbSet<G_PART_DESCRIPTION> G_PART_DESCRIPTION { get; set; }
        public virtual DbSet<G_PART_SUPERSESSION_ALL> G_PART_SUPERSESSION_ALL { get; set; }
        public virtual DbSet<P_ADDR_DFLT> P_ADDR_DFLT { get; set; }
        public virtual DbSet<P_ADDR_SPL> P_ADDR_SPL { get; set; }
        public virtual DbSet<P_ASN> P_ASN { get; set; }
        public virtual DbSet<P_ASN_INTERPDC> P_ASN_INTERPDC { get; set; }
        public virtual DbSet<P_CATALOG_CUSTOMER_PART> P_CATALOG_CUSTOMER_PART { get; set; }
        public virtual DbSet<R_ADDR_DFLT> R_ADDR_DFLT { get; set; }
        public virtual DbSet<R_ADDR_SPL> R_ADDR_SPL { get; set; }
        public virtual DbSet<R_ASN> R_ASN { get; set; }
        public virtual DbSet<R_CATALOG_CUSTOMER_PART> R_CATALOG_CUSTOMER_PART { get; set; }
        public virtual DbSet<V_ALIAS_ADDR_DFLT> V_ALIAS_ADDR_DFLT { get; set; }
        public virtual DbSet<V_ALIAS_ADDR_SPL> V_ALIAS_ADDR_SPL { get; set; }
        public virtual DbSet<V_CHK_DURATION_MISSING> V_CHK_DURATION_MISSING { get; set; }
        public virtual DbSet<V_NAV_ALL> V_NAV_ALL { get; set; }
        public virtual DbSet<V_USER_PAGE_LINK> V_USER_PAGE_LINK { get; set; }
        public virtual DbSet<V_USER_NAV_ALL> V_USER_NAV_ALL { get; set; }
    }
}
