//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTM_HS_CODE_MASTER
    {
        public string PART_NO { get; set; }
        public string DECLARATION_NAME { get; set; }
        public string HSCODE { get; set; }
        public string UOM { get; set; }
        public string ELEMENT { get; set; }
        public string FLEX3 { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> ACTIVITY_DATE { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public Nullable<decimal> SENT_TO_CTM { get; set; }
        public Nullable<System.DateTime> SENT_DATE { get; set; }
        public string COL_1 { get; set; }
        public string COL_2 { get; set; }
        public string COL_3 { get; set; }
        public string ENTITY { get; set; }
    }
}
