//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTM_EXPORT_STAGE_REPORT
    {
        public string CUSTOMER_NO { get; set; }
        public string ABBREVIATION { get; set; }
        public string LODNUM { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public string PN_GOMS { get; set; }
        public string PN_RP { get; set; }
        public string SUPPLIER_PN { get; set; }
        public string SHIP_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal QTY { get; set; }
        public Nullable<decimal> UNIT_PRICE_IN_USD { get; set; }
        public Nullable<decimal> PREMIUM_CHARGE_IN_USD { get; set; }
        public Nullable<decimal> UNIT_WEIGHT { get; set; }
        public Nullable<decimal> NET_WEIGHT { get; set; }
        public Nullable<decimal> GROSS_WEIGHT { get; set; }
        public string LWH { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string CARNAM { get; set; }
        public string DUE_DATE_CODE { get; set; }
        public string ORDER_NO { get; set; }
        public string CUSTOMER_PO_NO { get; set; }
        public string SHIP_TO_NAME { get; set; }
        public string SHIP_TO_ADDR_1 { get; set; }
        public string SHIP_TO_ADDR_2 { get; set; }
        public string SHIP_TO_ADDR_3 { get; set; }
        public string SHIP_TO_CONTACT { get; set; }
        public string SHIP_TO_CITY { get; set; }
        public string SHIP_TO_COUNTRY { get; set; }
        public string SHIP_TO_PHONE { get; set; }
        public string SHIP_TO_ZIP { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public Nullable<decimal> SENT_TO_CTM { get; set; }
        public Nullable<System.DateTime> SENT_DATE { get; set; }
        public string COL_1 { get; set; }
        public string COL_2 { get; set; }
        public string COL_3 { get; set; }
        public string ENTITY { get; set; }
    }
}
