//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTM_INB_ASN_INTERPDC
    {
        public string SITE { get; set; }
        public string CUSTOMER_NO { get; set; }
        public string ABBREVIATION { get; set; }
        public string SHIP_TO_NAME { get; set; }
        public string SHIP_TO_CITY { get; set; }
        public string DUE_DATE_CODE { get; set; }
        public long SHIPMENT_NO { get; set; }
        public long SHIPMENT_LINE_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<long> INVOICE_ITEM { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<decimal> WEIGHT_SHIPPED { get; set; }
        public string PACKING_LIST_NO { get; set; }
        public string CARRIER_CODE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public string PART_NO { get; set; }
        public string RP_PART { get; set; }
        public string DESCRIPTION { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string HARM_TRF_CD { get; set; }
        public Nullable<decimal> PART_WEIGHT { get; set; }
        public Nullable<decimal> QTY_SHIPPED { get; set; }
        public Nullable<decimal> ENT_TOTAL_LINE_AMT { get; set; }
        public Nullable<decimal> INVOICE_QTY { get; set; }
        public Nullable<decimal> UNIT_PRICE_AMT { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<decimal> INV_LINE_VALUE { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public Nullable<decimal> SENT_TO_CTM { get; set; }
        public Nullable<System.DateTime> SENT_DATE { get; set; }
        public string COL_1 { get; set; }
        public string COL_2 { get; set; }
        public string COL_3 { get; set; }
        public string ENTITY { get; set; }
    }
}
