//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EML_BASE
    {
        public string EML_ID { get; set; }
        public string EML_DESC { get; set; }
        public string TO_LIST { get; set; }
        public string CC_LIST { get; set; }
        public string EML_SUBJECT { get; set; }
        public string EML_CONTENT1 { get; set; }
        public string EML_CONTENT2 { get; set; }
        public string EML_CONTENT3 { get; set; }
        public string FOLDER { get; set; }
        public string SENDER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual EML_TASK EML_TASK { get; set; }
    }
}
