//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EML_TASK_TEMPLATE
    {
        public string TEMPLATE_ID { get; set; }
        public string EML_TASK_DESC { get; set; }
        public string EML_ID { get; set; }
        public string SQL { get; set; }
        public string OUT_TYPE { get; set; }
        public string FNAME { get; set; }
        public string IN_CONTENT { get; set; }
        public string SEND_NO_DATA { get; set; }
        public string DOC_NO { get; set; }
    
        public virtual EML_BASE EML_BASE { get; set; }
    }
}
