//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EW_LOG
    {
        public string MESSAGE_ID { get; set; }
        public string STATUS { get; set; }
        public string ERR_MSG { get; set; }
        public System.DateTime LOG_DATE { get; set; }
    }
}
