//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EW_MESSAGE_ATTACH
    {
        public string MESSAGE_ID { get; set; }
        public string SCRIPT_ID { get; set; }
        public string ACTIVEIND { get; set; }
        public string IN_CONTENT { get; set; }
        public string NO_DATA_IGNORE { get; set; }
    
        public virtual EW_MESSAGE EW_MESSAGE { get; set; }
        public virtual EW_SCRIPT EW_SCRIPT { get; set; }
    }
}
