//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EW_MESSAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EW_MESSAGE()
        {
            this.EW_MESSAGE_ATTACH = new HashSet<EW_MESSAGE_ATTACH>();
            this.EW_SCHEDULE_TASK = new HashSet<EW_SCHEDULE_TASK>();
            this.EW_USER_APPLY = new HashSet<EW_USER_APPLY>();
        }
    
        public string MESSAGE_ID { get; set; }
        public string MESSAGE_SUBJECT { get; set; }
        public string TO_LIST { get; set; }
        public string CC_LIST { get; set; }
        public string MESSAGE_TEXT1 { get; set; }
        public string MESSAGE_TEXT2 { get; set; }
        public string MESSAGE_TEXT3 { get; set; }
        public string MESSAGE_TEXT4 { get; set; }
        public string MESSAGE_TEXT5 { get; set; }
        public string MESSAGE_TEXT6 { get; set; }
        public string MESSAGE_TEXT7 { get; set; }
        public string MESSAGE_TEXT8 { get; set; }
        public string OWNER { get; set; }
        public string ACTIVEIND { get; set; }
        public string EW_GROUP { get; set; }
        public string MESSAGE_DESC_SHORT { get; set; }
        public string MESSAGE_DESC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EW_MESSAGE_ATTACH> EW_MESSAGE_ATTACH { get; set; }
        public virtual EW_MESSAGE_GROUP EW_MESSAGE_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EW_SCHEDULE_TASK> EW_SCHEDULE_TASK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EW_USER_APPLY> EW_USER_APPLY { get; set; }
    }
}
