//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EW_SCHEDULE_TASK
    {
        public string EW_SCHEDULE_ID { get; set; }
        public string MESSAGE_ID { get; set; }
        public string ACTIVEIND { get; set; }
    
        public virtual EW_MESSAGE EW_MESSAGE { get; set; }
        public virtual EW_SCHEDULE EW_SCHEDULE { get; set; }
    }
}
