//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EW_SCRIPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EW_SCRIPT()
        {
            this.EW_MESSAGE_ATTACH = new HashSet<EW_MESSAGE_ATTACH>();
        }
    
        public string SCRIPT_ID { get; set; }
        public string SCRIPT_DESC { get; set; }
        public string SCRIPT_TEXT { get; set; }
        public string ACTIVEIND { get; set; }
        public string OWNER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string EXPORT_FNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EW_MESSAGE_ATTACH> EW_MESSAGE_ATTACH { get; set; }
    }
}
