//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_KITS_LOAD
    {
        public string PARENT_PART { get; set; }
        public string COMPONENT_PART { get; set; }
        public string COMPONENT_PRINT_NO { get; set; }
        public string COMPONENT_COO { get; set; }
        public string COMPONENT_DESC { get; set; }
        public string COMPONENT_DESC_CN { get; set; }
        public long LINE_ITEM_NO { get; set; }
        public Nullable<System.DateTime> EFF_PHASE_IN_DATE { get; set; }
        public Nullable<System.DateTime> EFF_PHASE_OUT_DATE { get; set; }
        public Nullable<decimal> QTY_PER_ASSEMBLY { get; set; }
        public string NOTE_TEXT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
