//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_PART_ADDTIONAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_PART_ADDTIONAL()
        {
            this.IA_PRT_NOTE_CUST = new HashSet<IA_PRT_NOTE_CUST>();
        }
    
        public string PART_NO { get; set; }
        public string PRINT_PART_NO { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string PAPER_ID { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> MOQ_OVERRIDE { get; set; }
        public string MSG_ADDT1 { get; set; }
        public string MSG_ADDT2 { get; set; }
        public string MSG_ADDT3 { get; set; }
        public string QC_NOTE { get; set; }
        public Nullable<decimal> PACKING_MOQ { get; set; }
    
        public virtual RP_LABEL_PAPER_TYPE RP_LABEL_PAPER_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IA_PRT_NOTE_CUST> IA_PRT_NOTE_CUST { get; set; }
    }
}
