//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_PART_SUPERSESSION_ALL
    {
        public string PART_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string SSC { get; set; }
        public System.DateTime PHASE_OUT_DATE { get; set; }
        public Nullable<long> SUPERSESSION_ID { get; set; }
        public string SUPERSESSION_STATUS { get; set; }
        public string SUPERSESSION_TYPE { get; set; }
        public string SUPERSEDING_PART_NO { get; set; }
        public string SUPERSEDING_PART_DESCRIPTION { get; set; }
        public string SSC_SUPERSEDING { get; set; }
        public Nullable<int> QTY_PER { get; set; }
        public Nullable<byte> PRIMARY_FLAG { get; set; }
        public string SUPERSEDING_PRINT_PART_NO { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
