//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_PART_DESCRIPTION
    {
        public string PART_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string PLANNER_BUYER { get; set; }
        public string UNIT_MEAS { get; set; }
        public string PART_STATUS { get; set; }
        public Nullable<byte> MAKE_TO_FLAG { get; set; }
        public Nullable<long> SPC_TYPE { get; set; }
        public Nullable<decimal> PART_HEIGHT { get; set; }
        public Nullable<decimal> PART_LENGTH { get; set; }
        public Nullable<decimal> PART_WIDTH { get; set; }
        public Nullable<decimal> PART_WEIGHT { get; set; }
        public string CURRENT_SALES_STATUS_CODE { get; set; }
        public string PRINT_PART_NO { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string DESC_CN { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string LWH { get; set; }
        public Nullable<decimal> MIN_ORDER_QTY { get; set; }
        public Nullable<decimal> QTY_IN_CARTON { get; set; }
        public string TRANSP_PART_CODE { get; set; }
        public string NOTE_TEXT { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public string REMARK4 { get; set; }
        public string REMARK5 { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
    }
}
