//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOMS_ASN_H
    {
        public string WAREHOUSE { get; set; }
        public string BUY_FROM_COMPANY { get; set; }
        public string COMPANY_NAME { get; set; }
        public string MANIFEST_ID { get; set; }
        public Nullable<System.DateTime> SHIPMENT_DATE { get; set; }
        public Nullable<System.DateTime> EST_DLVY_DATE { get; set; }
        public string MANIFEST_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string PRIMARY_BUSINESS { get; set; }
        public System.DateTime LOAD_DATE { get; set; }
        public Nullable<System.DateTime> DOCK_DATE { get; set; }
        public string DOCK_DATE_BY { get; set; }
        public string IND { get; set; }
        public string NOTE { get; set; }
        public string IHUB_DOCK { get; set; }
    }
}
