//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IA_2DSCAN_LOG
    {
        public string INPUT_STR { get; set; }
        public string PART_IDENTIFIED { get; set; }
        public System.DateTime SCAN_DATE { get; set; }
        public string IA_AUDITOR { get; set; }
    }
}
