//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IA_CODE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IA_CODE_TYPE()
        {
            this.IA_LOD_DTL = new HashSet<IA_LOD_DTL>();
            this.IA_LOD_DTL1 = new HashSet<IA_LOD_DTL>();
        }
    
        public string IA_CODE { get; set; }
        public string IA_CODE_DESC { get; set; }
        public string DPMO_FLAG { get; set; }
        public string ACTIVEIND { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string AUTO_FLAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IA_LOD_DTL> IA_LOD_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IA_LOD_DTL> IA_LOD_DTL1 { get; set; }
    }
}
