//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IA_LOD_DTL
    {
        public string LODNUM { get; set; }
        public string PRTNUM { get; set; }
        public decimal UNTQTY { get; set; }
        public Nullable<decimal> IA_QTY { get; set; }
        public string IA_CODE1 { get; set; }
        public string IA_CODE2 { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string QTY_DISPLAY { get; set; }
    
        public virtual IA_CODE_TYPE IA_CODE_TYPE { get; set; }
        public virtual IA_CODE_TYPE IA_CODE_TYPE1 { get; set; }
        public virtual IA_LOD_HDR IA_LOD_HDR { get; set; }
    }
}
