//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IA_LOD_HDR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IA_LOD_HDR()
        {
            this.IA_LOD_DTL = new HashSet<IA_LOD_DTL>();
        }
    
        public string LODNUM { get; set; }
        public string WH_ID { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public string ADRNAM { get; set; }
        public string IA_STATUS { get; set; }
        public string IA_AUDITOR { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string LODNUM_DISPLAY { get; set; }
        public string SHIP_ID { get; set; }
        public Nullable<System.DateTime> COMPLETE_DATE { get; set; }
        public string COMP_COMMENTS { get; set; }
        public string SIGNER { get; set; }
        public string SIGN_COMMENTS { get; set; }
        public Nullable<System.DateTime> SIGN_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IA_LOD_DTL> IA_LOD_DTL { get; set; }
        public virtual IA_STATUS_CODE IA_STATUS_CODE { get; set; }
    }
}
