//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IA_LOD_AUDIT
    {
        public string LODNUM { get; set; }
        public string LODNUM_DISPLAY { get; set; }
        public string COMP_COMMENTS_NEW { get; set; }
        public string COMP_COMMENTS_OLD { get; set; }
        public string SIGNER_NEW { get; set; }
        public string SIGNER_OLD { get; set; }
        public string SIGN_COMMENTS_NEW { get; set; }
        public string SIGN_COMMENTS_OLD { get; set; }
        public Nullable<System.DateTime> ACTIVITY_DATE { get; set; }
    }
}
