//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IA_PRT_NOTE_CUST
    {
        public string PART_NO { get; set; }
        public string PRINT_PART_NO { get; set; }
        public string ADRNAM { get; set; }
        public string QC_NOTE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string USERID { get; set; }
        public string ACTIVEIND { get; set; }
    
        public virtual G_PART_ADDTIONAL G_PART_ADDTIONAL { get; set; }
        public virtual M_ADRNAM_MST M_ADRNAM_MST { get; set; }
    }
}
