//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IA_REPOSITORY_CLAIM_ORD
    {
        public string ADRNAM { get; set; }
        public string CUSTOMER_NO { get; set; }
        public string WAREHOUSE { get; set; }
        public string ORDER_NO { get; set; }
        public long LINE_NO { get; set; }
        public long RELEASE_NO { get; set; }
        public string CUSTOMER_PO_NO { get; set; }
        public string PART_NO { get; set; }
        public string PRINT_PART_NO { get; set; }
        public string DUE_DATE_CODE { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<System.DateTime> LINE_CREATED { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
