//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT_CUST_LOAD
    {
        public decimal LOAD_BATCH_TOKEN { get; set; }
        public string WILL_BILL_NO { get; set; }
        public string TC_GROUP { get; set; }
        public Nullable<System.DateTime> DO_RELEASE_DATE { get; set; }
        public Nullable<System.DateTime> BND_ARRIVAL_DATE { get; set; }
        public Nullable<System.DateTime> BND_OUT_DATE { get; set; }
        public Nullable<System.DateTime> NBND_ARRIVAL_DATE { get; set; }
        public string NOTE { get; set; }
        public string LOADED_BY { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
