//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT_EASY_QUERY_LOG
    {
        public decimal EASY_QUERY_TOKEN { get; set; }
        public System.DateTime QUERY_DATE { get; set; }
        public string PART_NO { get; set; }
        public string USER_ID { get; set; }
    }
}
