//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT_EASY_WATCHING
    {
        public decimal EASY_QUREY_TOKEN { get; set; }
        public string PART_NO { get; set; }
        public string WATCH_MSG { get; set; }
        public string WATCH_DETAIL { get; set; }
        public string COLOR { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
