//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class ITT_TRAN_LOAD
    {
        public decimal LOAD_BATCH_TOKEN { get; set; }
        public string WILL_BILL_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<System.DateTime> DEPART_DATE { get; set; }
        public Nullable<System.DateTime> ARRIVAL_DATE { get; set; }
        public string NOTE { get; set; }
        public string TRAN_TYPE { get; set; }
        public string LOADED_BY { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public string FROM_SYSTEM { get; set; }
    
        [JsonIgnore]
        public virtual ITT_TRAN_TYPE ITT_TRAN_TYPE { get; set; }
        [JsonIgnore]
        public virtual M_SYSTEM M_SYSTEM { get; set; }
    }
}
