//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT_SUPPLIER_IN_SCOPE
    {
        public string COMPANY_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string IN_SCOPE { get; set; }
        public string DISPLAY_NAME { get; set; }
    }
}
