//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT_SHIPPING_H_SNAP
    {
        public string FROM_SYSTEM { get; set; }
        public long SHIPMENT_NO { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string TRAN_PROCESS_ID { get; set; }
    
        public virtual ITT_TRAN_PROCESS ITT_TRAN_PROCESS { get; set; }
    }
}
