//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT_TRAN_PROCESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITT_TRAN_PROCESS()
        {
            this.ITT_SHIPPING_H_SNAP = new HashSet<ITT_SHIPPING_H_SNAP>();
        }
    
        public decimal RULE_SEQ { get; set; }
        public string TRAN_PROCESS_ID { get; set; }
        public string PROCESS_DESC { get; set; }
        public string FROM_SYSTEM { get; set; }
        public string TRAN_TYPE { get; set; }
        public Nullable<decimal> S00_DEPART { get; set; }
        public Nullable<decimal> S10_PORT_ARRIVAL { get; set; }
        public Nullable<decimal> IND_G { get; set; }
        public Nullable<decimal> IND_Y { get; set; }
        public string ICON1 { get; set; }
        public string ICON2 { get; set; }
        public string TP_CATEGORY1 { get; set; }
        public string TP_CATEGORY2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITT_SHIPPING_H_SNAP> ITT_SHIPPING_H_SNAP { get; set; }
        public virtual M_SYSTEM M_SYSTEM { get; set; }
        public virtual ITT_TRAN_TYPE ITT_TRAN_TYPE { get; set; }
    }
}
