//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT_SO
    {
        public string FROM_SYSTEM { get; set; }
        public string ORDER_NO { get; set; }
        public string SHIP_TO_ABBR { get; set; }
        public long LINE_NO { get; set; }
        public string PART_NO { get; set; }
        public string CUSTOMER_PO_NO { get; set; }
        public Nullable<decimal> CUST_PO_LINE_NO { get; set; }
        public string DUE_DATE_CODE { get; set; }
        public Nullable<decimal> STATUS_CODE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<decimal> BUY_QTY { get; set; }
        public Nullable<System.DateTime> RDD { get; set; }
        public Nullable<System.DateTime> ESD { get; set; }
        public Nullable<decimal> QTY_RESERVED { get; set; }
        public Nullable<decimal> QTY_PICKED { get; set; }
        public Nullable<decimal> QTY_SHIPPED { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
