//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT_CUSTOM_PROCESS_BACKUP
    {
        public string CUSTOM_PROCESS_ID { get; set; }
        public string PROCESS_DESC { get; set; }
        public Nullable<decimal> S20_DO_RELEASE { get; set; }
        public Nullable<decimal> S30_BND_ARRIVAL { get; set; }
        public Nullable<decimal> S40_BND_OUT { get; set; }
        public Nullable<decimal> S50_NBND_ARRIVAL { get; set; }
        public Nullable<decimal> S60_AVL { get; set; }
        public Nullable<decimal> IND_G { get; set; }
        public Nullable<decimal> IND_Y { get; set; }
        public string ICON1 { get; set; }
        public string ICON2 { get; set; }
        public string ICON3 { get; set; }
        public string CP_CATEGORY1 { get; set; }
        public string CP_CATEGORY2 { get; set; }
        public string CP_CATEGORY3 { get; set; }
    }
}
