//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT_AVLDTE
    {
        public string MANIFEST_ID { get; set; }
        public string PART_NO { get; set; }
        public Nullable<System.DateTime> AVL_DATE { get; set; }
        public string WAREHOUSE { get; set; }
    }
}
