//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_ADDR_CONVERT
    {
        public decimal JID { get; set; }
        public string GOMS_ADDR { get; set; }
        public string CONVERTED_ADDR { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
    }
}
