//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_ASN_HISTORY2
    {
        public string SPPOORDERNO { get; set; }
        public string DEPTNO { get; set; }
        public string WHNO { get; set; }
        public string SUPPLIERNO { get; set; }
        public string BILLTYPE { get; set; }
        public string BIZTYPE { get; set; }
        public string ORDERMARK { get; set; }
        public string CUSTOMERNO { get; set; }
        public System.DateTime EFFECTIVEDATE { get; set; }
        public string RECEIVELEVEL { get; set; }
        public string ACCEPTUNQCFLAG { get; set; }
        public string BOXFLAG { get; set; }
        public string BOXNO { get; set; }
        public string BOXGOODSNO { get; set; }
        public string BOXGOODSQTY { get; set; }
        public string BOXSERIALNO { get; set; }
        public string PORETURNMODE { get; set; }
        public string CUSTOMSINFO { get; set; }
        public string DEPTGOODSNO { get; set; }
        public string ISVGOODSNO { get; set; }
        public decimal NUMAPPLICATION { get; set; }
        public string PACKAGESORT { get; set; }
        public string GOODSSTATUS { get; set; }
        public string BARCODETYPE { get; set; }
        public string SIDCHECKOUT { get; set; }
        public string QUALITYCHECKRATE { get; set; }
        public string CUSTOMERPIN { get; set; }
    }
}
