//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_ORD_HISTORY
    {
        public string ISVUUID { get; set; }
        public string ISVSOURCE { get; set; }
        public string SHOPNO { get; set; }
        public string BDOWNERNO { get; set; }
        public string DEPARTMENTNO { get; set; }
        public string WAREHOUSENO { get; set; }
        public string SHIPPERNO { get; set; }
        public string SALESPLATFORMORDERNO { get; set; }
        public string SALEPLATFORMSOURCE { get; set; }
        public Nullable<System.DateTime> SALESPLATFORMCREATETIME { get; set; }
        public string CONSIGNEENAME { get; set; }
        public string CONSIGNEEMOBILE { get; set; }
        public string CONSIGNEEPHONE { get; set; }
        public string CONSIGNEEEMAIL { get; set; }
        public Nullable<System.DateTime> EXPECTDATE { get; set; }
        public string ADDRESSPROVINCE { get; set; }
        public string ADDRESSCITY { get; set; }
        public string ADDRESSCOUNTY { get; set; }
        public string ADDRESSTOWN { get; set; }
        public string CONSIGNEEADDRESS { get; set; }
        public string CONSIGNEEPOSTCODE { get; set; }
        public string RECEIVABLE { get; set; }
        public string CONSIGNEEREMARK { get; set; }
        public string ORDERMARK { get; set; }
        public string THIRDWAYBILL { get; set; }
        public string PACKAGEMARK { get; set; }
        public string BUSINESSTYPE { get; set; }
        public string DESTINATIONCODE { get; set; }
        public string DESTINATIONNAME { get; set; }
        public string SENDWEBSITECODE { get; set; }
        public string SENDWEBSITENAME { get; set; }
        public string SENDMODE { get; set; }
        public string RECEIVEMODE { get; set; }
        public string APPOINTDELIVERYTIME { get; set; }
        public string INSUREDPRICEFLAG { get; set; }
        public string INSUREDVALUE { get; set; }
        public string INSUREDFEE { get; set; }
        public string THIRDPAYMENT { get; set; }
        public string MONTHLYACCOUNT { get; set; }
        public string SHIPMENT { get; set; }
        public string SELLERREMARK { get; set; }
        public string THIRDSITE { get; set; }
        public string GOODSNOS { get; set; }
        public Nullable<decimal> PRICES { get; set; }
        public decimal QUANTITIES { get; set; }
        public string PINACCOUNT { get; set; }
        public string CUSTOMERNO { get; set; }
        public string SOTYPE { get; set; }
        public string WH_ID { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public string PRTNUM { get; set; }
        public string ORDTYP { get; set; }
        public string CUST_NO { get; set; }
        public string CUST_TYPE { get; set; }
        public string VC_CPONUM { get; set; }
        public string VC_DLRPONUM { get; set; }
        public string LINE_NOTE { get; set; }
        public string CUSTOMER_PARTNO_DESC { get; set; }
        public string CUSTOMER_PARTNO { get; set; }
    }
}
