//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_ORD_HISTORY_HDR
    {
        public string WH_ID { get; set; }
        public string ISVUUID { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public string BATCH_ID { get; set; }
    }
}
