//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_PRT_MST
    {
        public string PRTNUM { get; set; }
        public string PART_NO { get; set; }
        public string SALES_CODE { get; set; }
        public string BARCODE { get; set; }
        public string CLASS3CODE { get; set; }
        public string DESC_CN { get; set; }
        public string DESCRIPTION { get; set; }
        public string MAKER { get; set; }
        public string COO { get; set; }
        public string MODULE { get; set; }
        public string PSIZE { get; set; }
        public string COLOR { get; set; }
        public Nullable<decimal> LENGH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
