//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_WB_HISTORY
    {
        public string BATCH_ID { get; set; }
        public decimal PICKLIST_NO { get; set; }
        public string ADDR_ID { get; set; }
        public string WAREHOUSE { get; set; }
        public string CARRIER_CODE { get; set; }
        public string PRIORITY_CODE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string SHIP_TO_CONTACT { get; set; }
        public string SHIP_TO_PHONE { get; set; }
        public string SHIP_TO_FAX { get; set; }
        public string LOCAL_SHIP_TO_NAME { get; set; }
        public string LOCAL_SHIP_TO_ADDR_1 { get; set; }
        public string LOCAL_SHIP_TO_ADDR_2 { get; set; }
        public string LOCAL_SHIP_TO_ADDR_3 { get; set; }
        public string LOCAL_SHIP_TO_CITY { get; set; }
    }
}
