//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ADRNAM_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_ADRNAM_MST()
        {
            this.IA_PRT_NOTE_CUST = new HashSet<IA_PRT_NOTE_CUST>();
        }
    
        public string ADRNAM { get; set; }
        public string NOTE { get; set; }
        public string QC_NOTE { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string LABEL_CODE { get; set; }
        public string IA_IGNORE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IA_PRT_NOTE_CUST> IA_PRT_NOTE_CUST { get; set; }
        public virtual RP_LABEL_TYPE2 RP_LABEL_TYPE2 { get; set; }
    }
}
