//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_APPS
    {
        public string APP_NAME { get; set; }
        public string APP_DISPLAY { get; set; }
        public string URL { get; set; }
        public string ACTIVEIND { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    }
}
