//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CALENDAR
    {
        public System.DateTime CAL_DATE { get; set; }
        public string WORK_DAY_FLAG { get; set; }
        public string COMMENTS { get; set; }
    }
}
