//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_INV_ARCH
    {
        public string SYS_ID { get; set; }
        public string PART_NO { get; set; }
        public string WAREHOUSE { get; set; }
        public string BAY_NO { get; set; }
        public Nullable<decimal> QTY_AVL { get; set; }
        public Nullable<decimal> QTY_ONHAND { get; set; }
        public Nullable<decimal> QTY_RESERVED { get; set; }
        public Nullable<decimal> QTY_IN_RECEIVING { get; set; }
        public Nullable<decimal> QTY_IN_QA { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
