//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SYSTEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_SYSTEM()
        {
            this.APP_CUST_ALIAS_LINK = new HashSet<APP_CUST_ALIAS_LINK>();
            this.APP_WH = new HashSet<APP_WH>();
            this.TS_OR_HEADER = new HashSet<TS_OR_HEADER>();
        }
    
        public string SYSID { get; set; }
        public string DESCRIPTION { get; set; }
        public string SYS_TYPE { get; set; }
        public string DB_LINK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_CUST_ALIAS_LINK> APP_CUST_ALIAS_LINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_WH> APP_WH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_OR_HEADER> TS_OR_HEADER { get; set; }
    }
}
