//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_ENTITY_ITEM
    {
        public string PRODUCT_GROUP_ID { get; set; }
        public string PART_NO { get; set; }
        public string PART_DESC { get; set; }
        public string PART_STATUS { get; set; }
        public string NOTE { get; set; }
        public string PROD_LINE { get; set; }
        public string PART_TYPE { get; set; }
        public string DESC_CN { get; set; }
    
        public virtual MD_PRODUCT_GROUP MD_PRODUCT_GROUP { get; set; }
    }
}
