//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_PRODUCT_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_PRODUCT_GROUP()
        {
            this.MD_ENTITY_ITEM = new HashSet<MD_ENTITY_ITEM>();
        }
    
        public string PRODUCT_GROUP_ID { get; set; }
        public string GROUP_DESC { get; set; }
        public string ACTIVEIND { get; set; }
        public string FIN_RESP_CODE { get; set; }
        public string FBC { get; set; }
        public string FSBC { get; set; }
        public string SOUCE_PLANT { get; set; }
        public string PLANNER { get; set; }
        public string SPC_MAJOR_CODE { get; set; }
        public string SPC_INTERMEDIATE_CODE { get; set; }
        public string SPC_MINIMUM_CODE { get; set; }
        public string MTO_FLAG { get; set; }
        public string PVC_CODE { get; set; }
        public string FLEX1 { get; set; }
        public string FLEX2 { get; set; }
        public string FLEX3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_ENTITY_ITEM> MD_ENTITY_ITEM { get; set; }
    }
}
