//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_PIM_SNAP
    {
        public string INVENTORY_ITEM_ID { get; set; }
        public string PART_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string FIN_RESP_CODE { get; set; }
        public string FIN_BUSINESS_CODE { get; set; }
        public string FIN_SUB_BUSINESS_CODE { get; set; }
        public string CURRENT_SSC { get; set; }
        public string SUPERSEDING_PART_NO { get; set; }
        public string PART_SHORT_DESC { get; set; }
        public string PRINT_PART_NO { get; set; }
        public string SOURCE_PLANT { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
