//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MV_SHIPMENT_D_ALL1ONE_4_PRT
    {
        public string SHIP_ID { get; set; }
        public string WH_ID { get; set; }
        public string HOST_EXT_ID { get; set; }
        public string SHPSTS { get; set; }
        public string SHPSTS_DESC { get; set; }
        public string CARCOD { get; set; }
        public string CARNAM { get; set; }
        public string TRACK_NUM { get; set; }
        public Nullable<System.DateTime> ADDDTE { get; set; }
        public Nullable<System.DateTime> ALCDTE { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public Nullable<System.DateTime> LODDTE { get; set; }
        public Nullable<System.DateTime> ENTDTE { get; set; }
        public Nullable<System.DateTime> MODDTE { get; set; }
        public string MOD_USR_ID { get; set; }
        public string ADRNAM { get; set; }
        public string ADRLN1 { get; set; }
        public string ADRLN2 { get; set; }
        public string ADRLN3 { get; set; }
        public string ADRCTY { get; set; }
        public string ADRSTC { get; set; }
        public string ADRPSZ { get; set; }
        public string CTRY_NAME { get; set; }
        public string PHNNUM { get; set; }
        public string EMAIL_ADR { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string CONT_NAME { get; set; }
        public string SHIP_LINE_ID { get; set; }
        public string ORDNUM { get; set; }
        public string ORDLIN { get; set; }
        public string ORDSLN { get; set; }
        public Nullable<int> PCKQTY { get; set; }
        public Nullable<int> INPQTY { get; set; }
        public Nullable<int> STGQTY { get; set; }
        public Nullable<int> SHPQTY { get; set; }
        public string PRTNUM { get; set; }
        public string ORGCOD { get; set; }
        public Nullable<int> UNTQTY { get; set; }
        public string LODNUM { get; set; }
        public string SUBNUM { get; set; }
        public string BTCUST { get; set; }
        public string STCUST { get; set; }
        public string ORDTYP { get; set; }
        public string SALES_ORDNUM { get; set; }
        public string CSTPRT { get; set; }
        public string VC_CPONUM { get; set; }
        public string VC_CPOLIN { get; set; }
        public string VC_DLRPONUM { get; set; }
        public string STOLOC { get; set; }
        public Nullable<decimal> VC_PALWGT { get; set; }
        public Nullable<int> VC_PALLEN { get; set; }
        public Nullable<int> VC_PALWID { get; set; }
        public Nullable<int> VC_PALHGT { get; set; }
    }
}
