//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ASN
    {
        public string SYSID { get; set; }
        public string BUY_FROM_COMPANY { get; set; }
        public string MANIFEST_ID { get; set; }
        public long MANIFEST_LINE_NO { get; set; }
        public string WAY_BILL_ID { get; set; }
        public string BILL_OF_LADING_ID { get; set; }
        public string MASTER_BILL_ID { get; set; }
        public string PACKING_SEAL_ID { get; set; }
        public Nullable<System.DateTime> SHIPMENT_DATE { get; set; }
        public Nullable<System.DateTime> EST_DLVY_DATE { get; set; }
        public string WAREHOUSE { get; set; }
        public string MANIFEST_CODE { get; set; }
        public Nullable<byte> CLOSE_FLAG { get; set; }
        public Nullable<byte> ER_HOLD_FLAG { get; set; }
        public string PART_NO { get; set; }
        public string MSC_CODE { get; set; }
        public string PUR_ORDER_ID { get; set; }
        public Nullable<long> PUR_ORDER_LINE_NO { get; set; }
        public Nullable<long> PUR_ORDER_REL_NO { get; set; }
        public string PACKING_LIST_ID { get; set; }
        public Nullable<decimal> QTY_SHIPPED { get; set; }
        public Nullable<decimal> QTY_RECEIVED { get; set; }
        public Nullable<decimal> QTY_ADJUSTED { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> CORE_UNIT_PRICE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
    }
}
