//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_COST_SNAP
    {
        public Nullable<System.DateTime> COST_DATE { get; set; }
        public string PART_NO { get; set; }
        public Nullable<decimal> LEVEL_MATERIAL { get; set; }
        public Nullable<decimal> TOTAL_LEVEL { get; set; }
    }
}
