//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_CAR_MST
    {
        public string WH_ID { get; set; }
        public string CARCOD { get; set; }
        public string CARNAM { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public string WAYBILL_ID { get; set; }
        public string SEND_TO_TMS { get; set; }
        public string CARNAM_SHORT { get; set; }
    
        public virtual RP_WAYBILL_TYPE RP_WAYBILL_TYPE { get; set; }
    }
}
