//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_LABEL_PAPER_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RP_LABEL_PAPER_TYPE()
        {
            this.G_PART_ADDTIONAL = new HashSet<G_PART_ADDTIONAL>();
        }
    
        public string PAPER_ID { get; set; }
        public string PAPER_DESC { get; set; }
        public string LABEL_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_PART_ADDTIONAL> G_PART_ADDTIONAL { get; set; }
        public virtual RP_LABEL_TYPE2 RP_LABEL_TYPE2 { get; set; }
    }
}
