//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_LABEL_TYPE
    {
        public string LABEL_CODE { get; set; }
        public string LABEL_DESC { get; set; }
        public string ACTIVEIND { get; set; }
        public string T01 { get; set; }
        public string T02 { get; set; }
        public string T03 { get; set; }
        public string T04 { get; set; }
        public string T05 { get; set; }
        public string T06 { get; set; }
        public string T07 { get; set; }
        public string T08 { get; set; }
        public string T09 { get; set; }
        public string T10 { get; set; }
        public string T11 { get; set; }
        public string T12 { get; set; }
        public decimal PAPER_HORIZONTAL { get; set; }
        public decimal PAPER_VERTICAL { get; set; }
        public string HEADER { get; set; }
    }
}
