//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_ORDTYP_MST
    {
        public string WH_ID { get; set; }
        public string ORDTYP { get; set; }
        public string ORDTYP_WB { get; set; }
    }
}
