//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class RP_PRINTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RP_PRINTER()
        {
            this.APP_WH = new HashSet<APP_WH>();
            this.RP_STATION = new HashSet<RP_STATION>();
            this.APP_USERS = new HashSet<APP_USERS>();
        }
    
        public string PRINTER_ID { get; set; }
        public string PRINTER_NAME { get; set; }
        public string PRINTER_DESC { get; set; }
        public string ACTIVEIND { get; set; }
        public string IP_ADDR { get; set; }
        public string SITE_NAME { get; set; }
        public string PAPER_ID { get; set; }
        public string LABEL_CODE { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_WH> APP_WH { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_STATION> RP_STATION { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_USERS> APP_USERS { get; set; }
        public virtual APP_SITES APP_SITES { get; set; }
        public virtual RP_LABEL_TYPE2 RP_LABEL_TYPE2 { get; set; }
        public virtual RP_LABEL_PAPER_TYPE RP_LABEL_PAPER_TYPE { get; set; }
    }
}
