//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_PACKAGE
    {
        public string PRTNUM { get; set; }
        public string PACK_BOX { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
