//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_SHIP_TRACK
    {
        public string WH_ID { get; set; }
        public string SHIP_ID { get; set; }
        public string TRACK_NUM_IHUB { get; set; }
        public System.DateTime RECORD_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string TRACK_NUM_BY_IHUB { get; set; }
    }
}
