//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_WAYBILL_BASICINFO
    {
        public string WH_ID { get; set; }
        public string COMPANY { get; set; }
        public string SENDER { get; set; }
        public string ADDRESS { get; set; }
        public string CONTACT { get; set; }
        public string TELEPHONE { get; set; }
        public string SIGNATURE { get; set; }
        public string NOTE1 { get; set; }
        public string NOTE2 { get; set; }
        public string NOTE3 { get; set; }
        public string NOTE4 { get; set; }
        public string NOTE5 { get; set; }
        public string HEADER1 { get; set; }
        public string HEADER2 { get; set; }
        public string HEADER3 { get; set; }
        public string FOOTER1 { get; set; }
        public string FOOTER2 { get; set; }
        public string FOOTER3 { get; set; }
        public string DETAIL_TITLE1 { get; set; }
        public string DETAIL_TITLE2 { get; set; }
        public string DETAIL_TITLE3 { get; set; }
        public string DETAIL_TITLE4 { get; set; }
        public string DETAIL_TITLE5 { get; set; }
    }
}
