//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNAP_LOD_TRACK
    {
        public string WH_ID { get; set; }
        public Nullable<System.DateTime> LODDTE { get; set; }
        public string SHIP_ID { get; set; }
        public string LODNUM { get; set; }
        public string TRACK_NUM { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
