//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNAP_OPENASN_STATUS
    {
        public string FROM_SYSTEM { get; set; }
        public string MANIFEST_ID { get; set; }
        public string WAREHOUSE { get; set; }
        public Nullable<byte> ER_HOLD_FLAG { get; set; }
        public Nullable<byte> CLOSE_FLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<decimal> COMP_RATIO { get; set; }
    }
}
