//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNAP_V_SHIP_LIST_ALL_R
    {
        public string FROM_SYSTEM { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public long SHIPMENT_NO { get; set; }
        public Nullable<long> SHIPMENT_LINE_NO { get; set; }
        public string CUSTOMER_NO { get; set; }
        public string CATEGORY1 { get; set; }
        public string CATEGORY2 { get; set; }
        public string CUSTOMER_TYPE_CODE { get; set; }
        public string SHIP_TO_ABBR { get; set; }
        public Nullable<int> DEST_LOCATION { get; set; }
        public string CARRIER_CODE { get; set; }
        public string SCAC_DESC { get; set; }
        public string CARRIER_PRO_NO { get; set; }
        public string TRAILER_NO { get; set; }
        public string SEAL_NO { get; set; }
        public Nullable<int> BILL_OF_LADING { get; set; }
        public string TRACKING_NO { get; set; }
        public string WAREHOUSE { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<long> LINE_NO { get; set; }
        public Nullable<long> REL_NO { get; set; }
        public Nullable<System.DateTime> DD_ON_HEADER { get; set; }
        public Nullable<System.DateTime> ORDER_LINE_CREATED { get; set; }
        public Nullable<System.DateTime> RDD_IN_LINE { get; set; }
        public string DDC_IN_LINE { get; set; }
        public string PRIORITY_CODE { get; set; }
        public string HHP_FLAG { get; set; }
        public string CUSTOMER_PO_NO { get; set; }
        public string CUST_PO_LINE_NO { get; set; }
        public string DEALER_PO_NO { get; set; }
        public string PART_NO { get; set; }
        public string PRINT_PART_NO { get; set; }
        public string CUSTOMER_PARTNO { get; set; }
        public string DESCRIPTION { get; set; }
        public string FIN_BUSINESS_CODE { get; set; }
        public string HMLDHHP { get; set; }
        public string FIN_SUB_BUSINESS_CODE { get; set; }
        public string PART_CATEGORY1 { get; set; }
        public string CDRX_FLAG { get; set; }
        public string TRANSP_PART_CODE { get; set; }
        public string ABC_CODE { get; set; }
        public string PVC_CODE { get; set; }
        public string PLANNER_BUYER { get; set; }
        public string DEFAULT_SUPPLIER { get; set; }
        public string LOCAL_TYPE { get; set; }
        public Nullable<decimal> QTY_SHIPPED { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string PACKING_LIST_NO { get; set; }
        public Nullable<decimal> WEIGHT_SHIPPED { get; set; }
        public Nullable<decimal> PALLET_LENGTH { get; set; }
        public Nullable<decimal> PALLET_WIDTH { get; set; }
        public Nullable<decimal> PALLET_HEIGHT { get; set; }
        public string PICK_LIST_NO { get; set; }
        public Nullable<System.DateTime> PICK_LIST_CREATED { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string SHIP_TO_NAME { get; set; }
        public string SHIP_TO_ADDR_1 { get; set; }
        public string SHIP_TO_ADDR_2 { get; set; }
        public string SHIP_TO_ATTEN { get; set; }
        public string SHIP_TO_CITY { get; set; }
        public string SHIP_TO_COUNTRY { get; set; }
        public string LOCAL_SHIP_TO_NAME { get; set; }
        public string LOCAL_SHIP_TO_CITY { get; set; }
        public string LOCAL_SHIP_TO_ADDR_1 { get; set; }
        public string LOCAL_SHIP_TO_ADDR_2 { get; set; }
        public string LOCAL_SHIP_TO_ADDR_3 { get; set; }
        public string SHIP_TO_ZIP { get; set; }
        public Nullable<decimal> PERIOD_NO { get; set; }
        public string DB_SO_NO { get; set; }
        public Nullable<int> DB_SO_LINE_NO { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
