//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_HSCODE_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TC_HSCODE_MST()
        {
            this.TC_PART_HS = new HashSet<TC_PART_HS>();
        }
    
        public string HSCODE { get; set; }
        public string HSCODE_DESC { get; set; }
        public string TC_CATEGORY_ID { get; set; }
        public string NOTE1 { get; set; }
        public string NOTE2 { get; set; }
        public string NOTE3 { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<decimal> TAX_REFUND_RATE { get; set; }
    
        public virtual TC_PART_CATEGORY TC_PART_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_PART_HS> TC_PART_HS { get; set; }
    }
}
