//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_HSCODE_AUDIT
    {
        public string HSCODE { get; set; }
        public string OLD_TC_CATEGORY_ID { get; set; }
        public string OLD_HSCODE_DESC { get; set; }
        public string NEW_TC_CATEGORY_ID { get; set; }
        public string NEW_HACODE_DESC { get; set; }
        public Nullable<System.DateTime> ACTIVITY_DATE { get; set; }
    }
}
