//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_PART_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TC_PART_CATEGORY()
        {
            this.TC_PART_CATEGORY_STG = new HashSet<TC_PART_CATEGORY_STG>();
            this.M_PART = new HashSet<M_PART>();
            this.M_PART1 = new HashSet<M_PART>();
        }
    
        public string TC_CATEGORY_ID { get; set; }
        public string CATEGORY_DESC { get; set; }
        public string CATEGORY_NOTE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_PART_CATEGORY_STG> TC_PART_CATEGORY_STG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PART> M_PART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PART> M_PART1 { get; set; }
    }
}
