//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_PART_HS_INI
    {
        public string PART_NO { get; set; }
        public string DECLARATION_NAME { get; set; }
        public string HSCODE { get; set; }
        public Nullable<decimal> MFN_RATE { get; set; }
        public Nullable<decimal> TAX_RATE { get; set; }
        public Nullable<decimal> TAX_REFUND_RATE { get; set; }
        public string UOM { get; set; }
        public string ELEMENT { get; set; }
        public string PRE_CODING1 { get; set; }
        public string PRE_CODING2 { get; set; }
        public string PRE_CODING3 { get; set; }
        public string REGULATION { get; set; }
        public string INSPECTION { get; set; }
        public string EXPERTISE { get; set; }
        public string VOLTAGE { get; set; }
        public string NOTE1 { get; set; }
        public string NOTE2 { get; set; }
        public string NOTE3 { get; set; }
        public string FLEX1 { get; set; }
        public string FLEX2 { get; set; }
        public string FLEX3 { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
