//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_PART_HS_AUDIT
    {
        public string PART_NO { get; set; }
        public System.DateTime ACTIVITY_DATE { get; set; }
        public string AUDIT_FIELD { get; set; }
        public string N_VALUE { get; set; }
        public string O_VALUE { get; set; }
    }
}
