//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_DCECPRT_EXPORT
    {
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public long SHIPMENT_NO { get; set; }
        public string CUSTOMER_NO { get; set; }
        public string CATEGORY1 { get; set; }
        public string PART_NO { get; set; }
        public Nullable<decimal> QTY_SHIPPED { get; set; }
        public string SHIP_TO_NAME { get; set; }
    }
}
