//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_WO_HDR
    {
        public string WORK_ORDER_NO { get; set; }
        public string PART_NO { get; set; }
        public Nullable<decimal> QTY_COMPLETE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
