//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_SHIP_UPLOAD_STG
    {
        public string BU { get; set; }
        public Nullable<System.DateTime> GENERATED_DATE { get; set; }
        public string SHIP_ID { get; set; }
        public string WH_ID { get; set; }
        public string COMPANY { get; set; }
        public string CUST_NO { get; set; }
        public string CARCOD { get; set; }
        public string CARNAM_SHORT { get; set; }
        public string TRACK_NUM { get; set; }
        public Nullable<System.DateTime> LODDTE { get; set; }
        public string ADRNAM { get; set; }
        public string ADRLN1 { get; set; }
        public string ADRLN2 { get; set; }
        public string ADRLN3 { get; set; }
        public string ADRCTY { get; set; }
        public string ADRPSZ { get; set; }
        public string PHNNUM { get; set; }
        public string PHNNUM2 { get; set; }
        public string EMAIL_ADR { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<decimal> BOXES { get; set; }
        public Nullable<decimal> VC_PALWGT { get; set; }
        public Nullable<decimal> VOL_M3 { get; set; }
        public string NOTE { get; set; }
        public string FLEXFIELD1 { get; set; }
        public string FLEXFIELD2 { get; set; }
        public string SENT_TO_TMS { get; set; }
        public Nullable<decimal> SENT_DATE { get; set; }
    }
}
