//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_ADR_AUTO_CORRECT
    {
        public string ADRNAM { get; set; }
        public string ADRLN1 { get; set; }
        public string ADRCTY_CORRECT { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
