//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_OR_DETAIL_STAGE
    {
        public decimal ORDER_REQ_NO { get; set; }
        public decimal ORDER_LINE_NO { get; set; }
        public decimal SHIPFROM_SEQ { get; set; }
        public string PART_NO { get; set; }
        public string CUSTOMER_PART_NO { get; set; }
        public decimal BUY_QTY { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
