//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_ORDER_DETAIL_STG
    {
        public string PART_NO { get; set; }
        public string CUSTOMER_PART_NO { get; set; }
        public decimal BUY_QTY { get; set; }
        public string DESCRIPTION { get; set; }
        public string WAREHOUSE { get; set; }
        public decimal TOKEN_ID { get; set; }
    }
}
