//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ALIAS_ADDR_SPL
    {
        public string ALIAS_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string SYSID { get; set; }
        public string CUSTOMER_NO { get; set; }
        public string NAME { get; set; }
        public string ACTIVEIND { get; set; }
        public Nullable<int> BILL_TO_LOCATION { get; set; }
        public Nullable<long> SHIP_TO_LOCATION { get; set; }
        public Nullable<long> DEST_LOCATION { get; set; }
        public string DEST_NAME { get; set; }
        public string DEST_ADDR_1 { get; set; }
        public string DEST_ADDR_2 { get; set; }
        public string DEST_ADDR_3 { get; set; }
        public string DEST_CITY { get; set; }
        public string DEST_CONTACT { get; set; }
        public string DEST_PHONE { get; set; }
        public string DEST_FAX { get; set; }
        public string DEST_STATE { get; set; }
        public string DEST_COUNTRY { get; set; }
        public string DEST_ZIP { get; set; }
        public Nullable<System.DateTime> RECORD_DATE_OSD { get; set; }
        public string WAREHOUSE { get; set; }
        public string DEST_ATTENTION { get; set; }
        public string LOCAL_DEST_NAME { get; set; }
        public string LOCAL_DEST_ADDR_1 { get; set; }
        public string LOCAL_DEST_ADDR_2 { get; set; }
        public string LOCAL_DEST_ADDR_3 { get; set; }
        public string LOCAL_DEST_CITY { get; set; }
        public string LOCAL_DEST_COUNTRY { get; set; }
        public string LOCAL_DEST_STATE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE_OSDL { get; set; }
        public Nullable<decimal> DAYS { get; set; }
        public Nullable<decimal> DISTANCE { get; set; }
        public Nullable<byte> KG_FREIGHT { get; set; }
    }
}
