//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ALIAS_ADDR_DFLT
    {
        public string ALIAS_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string SYSID { get; set; }
        public string CUSTOMER_NO { get; set; }
        public string NAME { get; set; }
        public string ACTIVEIND { get; set; }
        public int BILL_TO_LOCATION { get; set; }
        public int SHIP_TO_LOCATION { get; set; }
        public string SHIP_TO_NAME { get; set; }
        public string SHIP_TO_ADDR_1 { get; set; }
        public string SHIP_TO_ADDR_2 { get; set; }
        public string SHIP_TO_ADDR_3 { get; set; }
        public string SHIP_TO_CONTACT { get; set; }
        public string SHIP_TO_PHONE { get; set; }
        public string SHIP_TO_FAX { get; set; }
        public string SHIP_TO_CITY { get; set; }
        public string SHIP_TO_STATE { get; set; }
        public string SHIP_TO_COUNTRY { get; set; }
        public string SHIP_TO_ZIP { get; set; }
        public Nullable<System.DateTime> RECORD_DATE_OS { get; set; }
        public string WAREHOUSE { get; set; }
        public string SHIP_TO_ATTEN { get; set; }
        public string LOCAL_SHIP_TO_NAME { get; set; }
        public string LOCAL_SHIP_TO_ADDR_1 { get; set; }
        public string LOCAL_SHIP_TO_ADDR_2 { get; set; }
        public string LOCAL_SHIP_TO_ADDR_3 { get; set; }
        public string LOCAL_SHIP_TO_CITY { get; set; }
        public string LOCAL_SHIP_TO_COUNTRY { get; set; }
        public string LOCAL_SHIP_TO_STATE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE_OSL { get; set; }
        public Nullable<decimal> DAYS { get; set; }
        public Nullable<decimal> DISTANCE { get; set; }
        public Nullable<byte> KG_FREIGHT { get; set; }
    }
}
