//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CHK_DUPLICATE_DEST
    {
        public string ALIAS_NAME { get; set; }
        public string SYSID { get; set; }
        public string CUSTOMER_NO { get; set; }
        public Nullable<int> BILL_TO_LOCATION { get; set; }
        public Nullable<long> SHIP_TO_LOCATION { get; set; }
        public string DEST_NAME { get; set; }
        public string DEST_ADDR_1 { get; set; }
        public string DEST_ADDR_2 { get; set; }
        public string DEST_CITY { get; set; }
        public string DEST_ZIP { get; set; }
        public string DEST_STATE { get; set; }
        public string DEST_COUNTRY { get; set; }
        public Nullable<decimal> DUPLICATE { get; set; }
        public string LOCAL_ADDR { get; set; }
    }
}
