//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CP_LOOKUP
    {
        public string FROM_SYSTEM { get; set; }
        public long SHIPMENT_NO { get; set; }
        public long SHIPMENT_LINE_NO { get; set; }
        public string TRAN_TYPE { get; set; }
        public string SHIP_TO_ABBR { get; set; }
        public string TC_CATEGORY_BY_MAN { get; set; }
        public string CUSTOM_PROCESS_ID { get; set; }
    }
}
