//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DURATION_WH2CITY
    {
        public string WAREHOUSE { get; set; }
        public string WH_DESC { get; set; }
        public string FROM_SITE { get; set; }
        public string TO_CITY { get; set; }
        public decimal DAYS { get; set; }
        public Nullable<decimal> DISTANCE { get; set; }
        public Nullable<byte> KG_FREIGHT { get; set; }
        public string PROVINCE { get; set; }
    }
}
