//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IA_TODO_TODAY
    {
        public Nullable<decimal> SEVERITY { get; set; }
        public string WH_ID { get; set; }
        public string SHIP_ID { get; set; }
        public string LODNUM { get; set; }
        public string LODNUM_DISPLAY { get; set; }
        public string CARCOD { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public string ADRNAM { get; set; }
        public string QC_NOTE_CUST { get; set; }
        public string ORDTYP { get; set; }
        public Nullable<decimal> CLAIM_CNT { get; set; }
        public Nullable<decimal> PART_NOTE_CNT { get; set; }
        public Nullable<decimal> LINES { get; set; }
        public string FLEX1 { get; set; }
        public string FLEX2 { get; set; }
        public string FLEX3 { get; set; }
        public string IA_STATUS { get; set; }
        public string STATUS_DESC { get; set; }
        public string IA_AUDITOR { get; set; }
        public string COMMENTS { get; set; }
    }
}
