//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IA_REPORT_PRINT
    {
        public string LODNUM { get; set; }
        public string WH_ID { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public string ADRNAM { get; set; }
        public string IA_STATUS { get; set; }
        public string STATUS_DESC { get; set; }
        public string IA_AUDITOR { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string LODNUM_DISPLAY { get; set; }
        public Nullable<System.DateTime> COMPLETE_DATE { get; set; }
        public string PRTNUM { get; set; }
        public decimal UNTQTY { get; set; }
        public Nullable<decimal> IA_QTY { get; set; }
        public string IA_CODE1 { get; set; }
        public string IA_CODE2 { get; set; }
        public string LINE_NOTE { get; set; }
        public string QTY_DISPLAY { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESC_CN { get; set; }
        public Nullable<decimal> PAPER_H { get; set; }
        public Nullable<decimal> PAPER_V { get; set; }
        public string H01 { get; set; }
        public string H02 { get; set; }
        public string H03 { get; set; }
        public string H04 { get; set; }
        public string H05 { get; set; }
        public string H06 { get; set; }
        public string H07 { get; set; }
        public string H08 { get; set; }
        public string H09 { get; set; }
        public string H10 { get; set; }
        public string H11 { get; set; }
        public string H12 { get; set; }
        public string T1 { get; set; }
        public string T2 { get; set; }
        public string T3 { get; set; }
        public string T4 { get; set; }
        public string T5 { get; set; }
        public string T6 { get; set; }
        public string T7 { get; set; }
        public string T8 { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string D3 { get; set; }
        public string D4 { get; set; }
        public string D5 { get; set; }
        public string D6 { get; set; }
        public string D7 { get; set; }
        public string D8 { get; set; }
        public string FOOTER { get; set; }
    }
}
