//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IA_PRT_NOTE_CUST_ADDNEW
    {
        public string PART_NO { get; set; }
        public string PRINT_PART_NO { get; set; }
        public string ADRNAM { get; set; }
        public string QC_NOTE { get; set; }
    }
}
