//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IA_LOD_HDR
    {
        public string LODNUM { get; set; }
        public string WH_ID { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public string ADRNAM { get; set; }
        public string IA_STATUS { get; set; }
        public string IA_AUDITOR { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string LODNUM_DISPLAY { get; set; }
        public string SHIP_ID { get; set; }
        public Nullable<System.DateTime> COMPLETE_DATE { get; set; }
        public string COMP_COMMENTS { get; set; }
        public string SIGNER { get; set; }
        public string SIGN_COMMENTS { get; set; }
        public Nullable<System.DateTime> SIGN_DATE { get; set; }
        public string NEED_SIGN_YN { get; set; }
        public string STATUS_DESC { get; set; }
    }
}
