//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IA_SIGN_IND
    {
        public string LODNUM { get; set; }
        public Nullable<decimal> IA_CODE1_IND { get; set; }
        public Nullable<decimal> IA_CODE2_IND { get; set; }
        public Nullable<decimal> QTY_IND { get; set; }
        public Nullable<decimal> NOTE_IND { get; set; }
    }
}
