//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IA_ALL
    {
        public string LODNUM { get; set; }
        public string LODNUM_DISPLAY { get; set; }
        public string WH_ID { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public string ADRNAM { get; set; }
        public string IA_STATUS { get; set; }
        public string STATUS_DESC { get; set; }
        public string IA_AUDITOR { get; set; }
        public string CUST_NOTE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string SHIP_ID { get; set; }
        public Nullable<System.DateTime> COMPLETE_DATE { get; set; }
        public string PRTNUM { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESC_CN { get; set; }
        public decimal UNTQTY { get; set; }
        public string QTY_DISPLAY { get; set; }
        public Nullable<decimal> IA_QTY { get; set; }
        public string IA_CODE1 { get; set; }
        public string IA_CODE2 { get; set; }
        public string QTY_RESULT { get; set; }
        public string LINE_NOTE { get; set; }
    }
}
