//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IHUB_CARRIER_ADVICE_BASE
    {
        public string WH_ID { get; set; }
        public string SHPSTS { get; set; }
        public string CARCOD { get; set; }
        public string CARNAM { get; set; }
        public string ORDTYP_WB { get; set; }
        public string ADDR_COMBINED { get; set; }
        public string SHIP_ID { get; set; }
        public Nullable<decimal> BOXES { get; set; }
        public Nullable<decimal> VCPAL_WGT { get; set; }
        public Nullable<decimal> VOL_WGT { get; set; }
        public Nullable<decimal> VOL_M3 { get; set; }
    }
}
