//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ITT_SHIPPING_ALLIN1_BACKUP
    {
        public string FROM_SYSTEM { get; set; }
        public long SHIPMENT_NO { get; set; }
        public long SHIPMENT_LINE_NO { get; set; }
        public System.DateTime SHIP_DATE { get; set; }
        public Nullable<decimal> BILL_OF_LADING { get; set; }
        public string SHIP_TO_ABBR { get; set; }
        public string CARRIER_CODE { get; set; }
        public string CARRIER_PRO_NO { get; set; }
        public Nullable<decimal> WEIGHT_SHIPPED { get; set; }
        public Nullable<int> NO_OF_CARTONS { get; set; }
        public string TRAN_TYPE { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<long> LINE_NO { get; set; }
        public string PART_NO { get; set; }
        public Nullable<decimal> QTY_SHIPPED { get; set; }
        public string SERIAL_NO { get; set; }
        public string PACKING_LIST_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<decimal> INVOICE_ITEM { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string SU_LP { get; set; }
        public string LODNUM { get; set; }
        public Nullable<System.DateTime> S00_DEPART_DATE { get; set; }
        public Nullable<System.DateTime> S10_PORT_ARRIVAL_DATE { get; set; }
        public Nullable<System.DateTime> S20_DO_RELEASE_DATE { get; set; }
        public Nullable<System.DateTime> S30_BND_ARRIVAL_DATE { get; set; }
        public Nullable<System.DateTime> S40_BND_OUT_DATE { get; set; }
        public Nullable<System.DateTime> S50_NBND_ARRIVAL_DATE { get; set; }
        public string TRACKING_NO { get; set; }
        public string WILL_BILL_NO { get; set; }
        public Nullable<System.DateTime> WB_LAST_CHANGED { get; set; }
        public string TRAN_PROCESS_ID { get; set; }
        public string CUSTOM_PROCESS_ID { get; set; }
        public Nullable<decimal> S00_DEPART_DAYS { get; set; }
        public Nullable<decimal> S10_PORT_ARRIVAL_DAYS { get; set; }
        public Nullable<decimal> S20_DO_RELEASE_DAYS { get; set; }
        public Nullable<decimal> S30_BND_ARRIVAL_DAYS { get; set; }
        public Nullable<decimal> S40_BND_OUT_DAYS { get; set; }
        public Nullable<decimal> S50_NBND_ARRIVAL_DAYS { get; set; }
    }
}
