//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_JD_ASN_LOAD
    {
        public string SPPOORDERNO { get; set; }
        public string DEPTNO { get; set; }
        public string WHNO { get; set; }
        public string SUPPLIERNO { get; set; }
        public string ORDERMARK { get; set; }
        public Nullable<System.DateTime> EFFECTIVEDATE { get; set; }
        public Nullable<decimal> PORETURNMODE { get; set; }
        public string ISVGOODSNO { get; set; }
        public Nullable<decimal> NUMAPPLICATION { get; set; }
        public Nullable<decimal> GOODSSTATUS { get; set; }
        public string CUSTOMERPIN { get; set; }
    }
}
