//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_JD_WB_FORMAT
    {
        public string 事业部编号 { get; set; }
        public decimal 商家订单编号 { get; set; }
        public Nullable<decimal> 产品类型 { get; set; }
        public string 寄件人简称 { get; set; }
        public string 收件人简称 { get; set; }
        public string 寄件人姓名 { get; set; }
        public string 寄件人手机号码 { get; set; }
        public string 寄件人固定电话 { get; set; }
        public string 寄件人公司 { get; set; }
        public string 寄件人地址 { get; set; }
        public string 收件人姓名 { get; set; }
        public string 收件人手机号码 { get; set; }
        public string 收件人固定电话 { get; set; }
        public string 收件人公司 { get; set; }
        public string 收件人地址 { get; set; }
        public string 寄托物品名称 { get; set; }
        public Nullable<decimal> 寄托物体积 { get; set; }
        public Nullable<decimal> 寄托物重量 { get; set; }
        public string 预计提货时间开始 { get; set; }
        public string 预计提货时间结束 { get; set; }
        public string 备注 { get; set; }
        public Nullable<decimal> 运费结算方式 { get; set; }
    }
}
