//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_JD_PICK_BASE
    {
        public string SHIP_ID { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public string WH_ID { get; set; }
        public string ORDTYP { get; set; }
        public string CARCOD { get; set; }
        public string CUST_NO { get; set; }
        public string ADRNAM { get; set; }
        public string ADR { get; set; }
        public string PHNNUM { get; set; }
        public string EMAIL_ADR { get; set; }
        public string LAST_NAME { get; set; }
        public string PRTNUM { get; set; }
        public string VC_CPONUM { get; set; }
        public string VC_DLRPONUM { get; set; }
        public Nullable<decimal> QTY { get; set; }
    }
}
