//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_JD_ASN_BASE
    {
        public string WAREHOUSE { get; set; }
        public string ASN_NO { get; set; }
        public string MANIFEST_CODE { get; set; }
        public string BUY_FROM_COMPANY { get; set; }
        public string CLIENT_ID { get; set; }
        public string PRTNUM { get; set; }
        public Nullable<decimal> EXPQTY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
