//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_JD_PICK_LOAD
    {
        public string ISVUUID { get; set; }
        public string ISVSOURCE { get; set; }
        public string SHOPNO { get; set; }
        public string DEPARTMENTNO { get; set; }
        public string WAREHOUSENO { get; set; }
        public Nullable<decimal> SALEPLATFORMSOURCE { get; set; }
        public Nullable<System.DateTime> SALESPLATFORMCREATETIME { get; set; }
        public string CONSIGNEENAME { get; set; }
        public string CONSIGNEEMOBILE { get; set; }
        public string CONSIGNEEPHONE { get; set; }
        public string CONSIGNEEEMAIL { get; set; }
        public string CONSIGNEEADDRESS { get; set; }
        public string CONSIGNEEREMARK { get; set; }
        public string ORDERMARK { get; set; }
        public Nullable<decimal> QUANTITIES { get; set; }
        public string PINACCOUNT { get; set; }
        public Nullable<decimal> SOTYPE { get; set; }
        public string WH_ID { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public string PRTNUM { get; set; }
        public string ORDTYP { get; set; }
        public string CUST_NO { get; set; }
        public string CUST_TYPE { get; set; }
        public string VC_CPONUM { get; set; }
        public string VC_DLRPONUM { get; set; }
        public string DESC_CN { get; set; }
        public string CUSTOMER_PARTNO { get; set; }
    }
}
