//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_JD_PRT_MST_LOAD
    {
        public string BU_CODE { get; set; }
        public string PRTNUM { get; set; }
        public string PART_NO { get; set; }
        public string BARCODE { get; set; }
        public string CLASS3CODE { get; set; }
        public string DESC_CN { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> PART_LENGTH { get; set; }
        public Nullable<decimal> PART_WIDTH { get; set; }
        public Nullable<decimal> PART_HEIGHT { get; set; }
        public Nullable<decimal> PART_WEIGHT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
