//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_KPI_HISTORY_ALL
    {
        public string KPI_GROUP { get; set; }
        public string KPI_GROUP_DESC { get; set; }
        public string KGROUP_IND { get; set; }
        public string KPI_CODE { get; set; }
        public string KPI_SUB_CODE { get; set; }
        public string KPI_DESC { get; set; }
        public string KPI_IND { get; set; }
        public System.DateTime KPI_DATE { get; set; }
        public decimal KPI_VALUE { get; set; }
        public Nullable<decimal> KPI_TARGET { get; set; }
        public Nullable<decimal> IND_Y { get; set; }
        public string KPI_OWNER { get; set; }
        public string NOTE { get; set; }
        public string OWNER_HIGHLIGHT { get; set; }
        public Nullable<System.DateTime> HIGHLIGHT_DATE { get; set; }
    }
}
