//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MD_PB_VALID
    {
        public long PRICE_BREAK_TOKEN { get; set; }
        public string PART_NO { get; set; }
        public string COMPANY_CODE { get; set; }
        public Nullable<System.DateTime> BEGIN_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string WAREHOUSE { get; set; }
    }
}
