//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_O_DOWNLOAD_DTL
    {
        public decimal ORDER_REQ_NO { get; set; }
        public decimal SHIPFROM_SEQ { get; set; }
        public decimal ORDER_LINE_NO { get; set; }
        public string TXT { get; set; }
    }
}
