//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OPEN_QTY_PO_PDC
    {
        public string WAREHOUSE { get; set; }
        public string WH_ALIAS { get; set; }
        public string BUY_FROM_COMPANY { get; set; }
        public string COMPANY_NAME { get; set; }
        public string PART_NO { get; set; }
        public Nullable<decimal> RELEASE_QTY { get; set; }
        public Nullable<decimal> REMAINING_QTY { get; set; }
    }
}
