//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PLABEL_BY_LOD_BASE
    {
        public string WH_ID { get; set; }
        public string SHIP_ID { get; set; }
        public string LODNUM { get; set; }
        public string SHPSTS { get; set; }
        public string SHPSTS_DESC { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public Nullable<System.DateTime> LODDTE { get; set; }
        public string ADRNAM { get; set; }
        public string ORGCOD { get; set; }
        public string PRTNUM { get; set; }
        public Nullable<decimal> UNTQTY { get; set; }
        public string VC_CPONUM { get; set; }
    }
}
