//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PLABEL_BY_KITS_BASE
    {
        public string PARENT_PART { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESC_CN { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string UNIT_MEAS { get; set; }
        public Nullable<decimal> PART_HEIGHT { get; set; }
        public Nullable<decimal> PART_LENGTH { get; set; }
        public Nullable<decimal> PART_WIDTH { get; set; }
        public Nullable<decimal> PART_WEIGHT { get; set; }
        public string PRINT_PART_NO { get; set; }
        public Nullable<decimal> MIN_ORDER_QTY { get; set; }
        public decimal QTY_IN_CARTON { get; set; }
        public string NOTE_TEXT { get; set; }
        public string COMPONENT_PART { get; set; }
        public string COMPONENT_PRINT_NO { get; set; }
        public string COMPONENT_COO { get; set; }
        public string COMPONENT_DESC { get; set; }
        public string COMPONENT_DESC_CN { get; set; }
        public long LINE_ITEM_NO { get; set; }
        public Nullable<System.DateTime> EFF_PHASE_IN_DATE { get; set; }
        public Nullable<System.DateTime> EFF_PHASE_OUT_DATE { get; set; }
        public Nullable<decimal> QTY_PER_ASSEMBLY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
    }
}
