//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PLABEL_BY_UNCATALOG_PRINT
    {
        public string NOTE { get; set; }
        public string PART_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESC_CN { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string UNIT_MEAS { get; set; }
        public string PART_STATUS { get; set; }
        public Nullable<decimal> PART_HEIGHT { get; set; }
        public Nullable<decimal> PART_LENGTH { get; set; }
        public Nullable<decimal> PART_WIDTH { get; set; }
        public Nullable<decimal> PART_WEIGHT { get; set; }
        public string CURRENT_SALES_STATUS_CODE { get; set; }
        public string PRINT_PART_NO { get; set; }
        public Nullable<decimal> MIN_ORDER_QTY { get; set; }
        public decimal QTY_IN_CARTON { get; set; }
        public Nullable<decimal> COPIES { get; set; }
        public string COUNTRY_DESC_CN { get; set; }
        public string LABEL_CODE { get; set; }
        public string LABEL_DESC { get; set; }
        public string ACTIVEIND { get; set; }
        public decimal PAPER_HORIZONTAL { get; set; }
        public decimal PAPER_VERTICAL { get; set; }
        public string C01 { get; set; }
        public string C02 { get; set; }
        public string C03 { get; set; }
        public string C04 { get; set; }
        public string C05 { get; set; }
        public string C06 { get; set; }
        public string C07 { get; set; }
        public string C08 { get; set; }
        public string C09 { get; set; }
        public string C10 { get; set; }
        public string C11 { get; set; }
        public string C12 { get; set; }
        public string C13 { get; set; }
        public string C14 { get; set; }
        public Nullable<decimal> C15 { get; set; }
        public string C16 { get; set; }
        public string C17 { get; set; }
        public string C18 { get; set; }
        public string C19 { get; set; }
        public string C20 { get; set; }
        public string C21 { get; set; }
        public string C22 { get; set; }
        public string C23 { get; set; }
        public string C24 { get; set; }
        public string T01 { get; set; }
        public string T02 { get; set; }
        public string T03 { get; set; }
        public string T04 { get; set; }
        public string T05 { get; set; }
        public string T06 { get; set; }
        public string T07 { get; set; }
        public string T08 { get; set; }
        public string T09 { get; set; }
        public string T10 { get; set; }
        public string T11 { get; set; }
        public string T12 { get; set; }
        public string T13 { get; set; }
        public string T14 { get; set; }
        public string T15 { get; set; }
        public string T16 { get; set; }
        public string T17 { get; set; }
        public string T18 { get; set; }
        public string T19 { get; set; }
        public string T20 { get; set; }
        public string T21 { get; set; }
        public string T22 { get; set; }
        public string T23 { get; set; }
        public string T24 { get; set; }
        public Nullable<decimal> PX01 { get; set; }
        public Nullable<decimal> PY01 { get; set; }
        public Nullable<decimal> PX02 { get; set; }
        public Nullable<decimal> PY02 { get; set; }
        public Nullable<decimal> PX03 { get; set; }
        public Nullable<decimal> PY03 { get; set; }
        public Nullable<decimal> PX04 { get; set; }
        public Nullable<decimal> PY04 { get; set; }
        public Nullable<decimal> PX05 { get; set; }
        public Nullable<decimal> PY05 { get; set; }
        public Nullable<decimal> PX06 { get; set; }
        public Nullable<decimal> PY06 { get; set; }
        public Nullable<decimal> PX07 { get; set; }
        public Nullable<decimal> PY07 { get; set; }
        public Nullable<decimal> PX08 { get; set; }
        public Nullable<decimal> PY08 { get; set; }
        public Nullable<decimal> PX09 { get; set; }
        public Nullable<decimal> PY09 { get; set; }
        public Nullable<decimal> PX10 { get; set; }
        public Nullable<decimal> PY10 { get; set; }
        public Nullable<decimal> PX11 { get; set; }
        public Nullable<decimal> PY11 { get; set; }
        public Nullable<decimal> PX12 { get; set; }
        public Nullable<decimal> PY12 { get; set; }
        public Nullable<decimal> PX13 { get; set; }
        public Nullable<decimal> PY13 { get; set; }
        public Nullable<decimal> PX14 { get; set; }
        public Nullable<decimal> PY14 { get; set; }
        public Nullable<decimal> PX15 { get; set; }
        public Nullable<decimal> PY15 { get; set; }
        public Nullable<decimal> PX16 { get; set; }
        public Nullable<decimal> PY16 { get; set; }
        public Nullable<decimal> PX17 { get; set; }
        public Nullable<decimal> PY17 { get; set; }
        public Nullable<decimal> PX18 { get; set; }
        public Nullable<decimal> PY18 { get; set; }
        public Nullable<decimal> PX19 { get; set; }
        public Nullable<decimal> PY19 { get; set; }
        public Nullable<decimal> PX20 { get; set; }
        public Nullable<decimal> PY20 { get; set; }
        public Nullable<decimal> PX21 { get; set; }
        public Nullable<decimal> PY21 { get; set; }
        public Nullable<decimal> PX22 { get; set; }
        public Nullable<decimal> PY22 { get; set; }
        public Nullable<decimal> PX23 { get; set; }
        public Nullable<decimal> PY23 { get; set; }
        public Nullable<decimal> PX24 { get; set; }
        public Nullable<decimal> PY24 { get; set; }
        public Nullable<decimal> S01 { get; set; }
        public Nullable<decimal> S02 { get; set; }
        public Nullable<decimal> S03 { get; set; }
        public Nullable<decimal> S04 { get; set; }
        public Nullable<decimal> S05 { get; set; }
        public Nullable<decimal> S06 { get; set; }
        public Nullable<decimal> S07 { get; set; }
        public Nullable<decimal> S08 { get; set; }
        public Nullable<decimal> S09 { get; set; }
        public Nullable<decimal> S10 { get; set; }
        public Nullable<decimal> S11 { get; set; }
        public Nullable<decimal> S12 { get; set; }
        public Nullable<decimal> S13 { get; set; }
        public Nullable<decimal> S14 { get; set; }
        public Nullable<decimal> S15 { get; set; }
        public Nullable<decimal> S16 { get; set; }
        public Nullable<decimal> S17 { get; set; }
        public Nullable<decimal> S18 { get; set; }
        public Nullable<decimal> S19 { get; set; }
        public Nullable<decimal> S20 { get; set; }
        public Nullable<decimal> S21 { get; set; }
        public Nullable<decimal> S22 { get; set; }
        public Nullable<decimal> S23 { get; set; }
        public Nullable<decimal> S24 { get; set; }
        public Nullable<decimal> SIZE_2D { get; set; }
        public string LG_PARTNO { get; set; }
        public string YT_PARTNO { get; set; }
    }
}
