//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PLABEL_PRINT_OLD
    {
        public string PART_CATALOG { get; set; }
        public string PART_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESC_CN { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string COUNTRY_DESC_CN { get; set; }
        public string UNIT_MEAS { get; set; }
        public string PART_STATUS { get; set; }
        public Nullable<decimal> PART_HEIGHT { get; set; }
        public Nullable<decimal> PART_LENGTH { get; set; }
        public Nullable<decimal> PART_WIDTH { get; set; }
        public Nullable<decimal> PART_WEIGHT { get; set; }
        public string CURRENT_SALES_STATUS_CODE { get; set; }
        public string PRINT_PART_NO { get; set; }
        public Nullable<decimal> MIN_ORDER_QTY { get; set; }
        public Nullable<decimal> QTY_IN_CARTON { get; set; }
        public string LG_PARTNO { get; set; }
        public string YT_PARTNO { get; set; }
        public string LABEL_CODE { get; set; }
        public string LABEL_DESC { get; set; }
        public string ACTIVEIND { get; set; }
        public decimal PAPER_HORIZONTAL { get; set; }
        public decimal PAPER_VERTICAL { get; set; }
        public string HEADER { get; set; }
        public string T01 { get; set; }
        public string T02 { get; set; }
        public string T03 { get; set; }
        public string T04 { get; set; }
        public string T05 { get; set; }
        public string T06 { get; set; }
        public string T07 { get; set; }
        public string T08 { get; set; }
        public string T09 { get; set; }
        public string T10 { get; set; }
        public string T11 { get; set; }
        public string T12 { get; set; }
        public string C01 { get; set; }
        public string C02 { get; set; }
        public string C03 { get; set; }
        public string C04 { get; set; }
        public string C05 { get; set; }
        public string C06 { get; set; }
        public string C07 { get; set; }
        public string C08 { get; set; }
        public string C09 { get; set; }
    }
}
