//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RP_WAYBILL_D_PRINT
    {
        public string WH_ID { get; set; }
        public string SHIP_ID { get; set; }
        public string LODNUM { get; set; }
        public Nullable<decimal> VC_PALWGT { get; set; }
        public Nullable<int> VC_PALLEN { get; set; }
        public Nullable<int> VC_PALWID { get; set; }
        public Nullable<int> VC_PALHGT { get; set; }
        public string PALVOL { get; set; }
        public Nullable<decimal> PALVOL_M3 { get; set; }
        public Nullable<decimal> QTYS { get; set; }
        public string VC_DLRPONUM { get; set; }
        public string VC_CPONUM { get; set; }
        public string REMARK1 { get; set; }
        public string REMKAR2 { get; set; }
    }
}
