//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SHIPPING_ALL_BASE
    {
        public string FROM_SYSTEM { get; set; }
        public string SHIP_TO_ABBR { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<long> LINE_NO { get; set; }
        public long SHIPMENT_NO { get; set; }
        public Nullable<long> SHIPMENT_LINE_NO { get; set; }
        public string PART_NO { get; set; }
        public Nullable<decimal> QTY_SHIPPED { get; set; }
        public string SERIAL_NO { get; set; }
        public System.DateTime SHIP_DATE { get; set; }
        public string PACKING_LIST_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<decimal> INVOICE_ITEM { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string SU_LP { get; set; }
        public string LODNUM { get; set; }
        public System.DateTime REMOTE_CREATE_DATE { get; set; }
        public Nullable<System.DateTime> LOCAL_CREATE_DATE { get; set; }
        public Nullable<System.DateTime> S40_BND_OUT_DATE { get; set; }
        public Nullable<System.DateTime> S50_NBND_ARRIVAL_DATE { get; set; }
        public Nullable<System.DateTime> FLEX_DATE { get; set; }
        public string NOTE { get; set; }
        public string TRACKING_NO { get; set; }
        public Nullable<System.DateTime> S00_DEPART_DATE { get; set; }
        public Nullable<System.DateTime> S10_PORT_ARRIVAL_DATE { get; set; }
        public Nullable<System.DateTime> S20_DO_RELEASE_DATE { get; set; }
        public Nullable<System.DateTime> S30_BND_ARRIVAL_DATE { get; set; }
        public string WILL_BILL_NO { get; set; }
        public Nullable<System.DateTime> WB_LAST_CHANGED { get; set; }
        public string TRAN_TYPE { get; set; }
    }
}
