//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SHIP_H_LINK_PROC
    {
        public string FROM_SYSTEM { get; set; }
        public long SHIPMENT_NO { get; set; }
        public Nullable<System.DateTime> SHIPMENT_DATE { get; set; }
        public Nullable<decimal> BILL_OF_LADING { get; set; }
        public string SHIP_TO_ABBR { get; set; }
        public string CARRIER_CODE { get; set; }
        public string CARRIER_PRO_NO { get; set; }
        public Nullable<decimal> WEIGHT_SHIPPED { get; set; }
        public Nullable<int> NO_OF_CARTONS { get; set; }
        public Nullable<System.DateTime> REMOTE_CREATE_DATE { get; set; }
        public string TRACKING_NO { get; set; }
        public Nullable<System.DateTime> LOCAL_CREATE_DATE { get; set; }
        public string NOTE { get; set; }
        public string TRAN_TYPE { get; set; }
        public Nullable<decimal> RULE_SEQ { get; set; }
        public string TRAN_PROCESS_ID { get; set; }
        public string PROCESS_DESC { get; set; }
        public Nullable<decimal> S00_DEPART { get; set; }
        public Nullable<decimal> S10_PORT_ARRIVAL { get; set; }
        public Nullable<decimal> IND_G { get; set; }
        public Nullable<decimal> IND_Y { get; set; }
        public string TP_CATEGORY1 { get; set; }
        public string TP_CATEGORY2 { get; set; }
    }
}
