//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SHIPMENT_SMRY_RP0
    {
        public string SHIP_ID { get; set; }
        public string WH_ID { get; set; }
        public string CUST_NO { get; set; }
        public string ORDTYP { get; set; }
        public string SHPSTS { get; set; }
        public Nullable<decimal> BOXES { get; set; }
        public Nullable<decimal> VC_PALWGT { get; set; }
        public Nullable<decimal> VOL_M3 { get; set; }
    }
}
