//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TC_CATEGORY_BY_SYS
    {
        public string PART_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime REMOTE_CREATE_DATE { get; set; }
        public string TC_CATEGORY_BY_SYS { get; set; }
    }
}
