//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TC_DB_SENDOUT_DAILY
    {
        public Nullable<System.DateTime> RUN_DAYE { get; set; }
        public string PART_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string DECLARATION_NAME { get; set; }
        public string HSCODE { get; set; }
        public string ELEMENT { get; set; }
        public string COL_CHANGED { get; set; }
        public System.DateTime ACTIVITY_DATE { get; set; }
    }
}
