//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TMP_QUICK_ORDER_SUMMARY
    {
        public Nullable<System.DateTime> REPORT_DATE { get; set; }
        public string WEEK { get; set; }
        public string ALIAS_NAME { get; set; }
        public Nullable<decimal> LINES_BY_IHUB { get; set; }
        public Nullable<decimal> TOTAL_LINES { get; set; }
        public string IHUUB_PERCENTAGE { get; set; }
    }
}
