//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USER_ALIAS_LINK
    {
        public string APP_USER { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL_ADDR { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string ALIAS_NAME { get; set; }
        public string DEFAULT_FLAG { get; set; }
    }
}
