//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USER_NAV_ALL
    {
        public string APP_USER { get; set; }
        public decimal DISPLAY_SEQ { get; set; }
        public string SPACE_CODE { get; set; }
        public string SPACE_DESC { get; set; }
        public string PAGE_NAME { get; set; }
        public string URL { get; set; }
        public string DISPLAY { get; set; }
        public string DESCRIPTION { get; set; }
        public string PUBLICIND { get; set; }
        public string VERION { get; set; }
        public string MOBILE { get; set; }
        public string ICON { get; set; }
        public string ICON_DESC { get; set; }
    }
}
