//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WO_RP1
    {
        public string WKONUM { get; set; }
        public string WH_ID { get; set; }
        public string PRTNUM { get; set; }
        public string ORGCOD { get; set; }
        public string WKOSTS { get; set; }
        public Nullable<System.DateTime> ENTDTE { get; set; }
        public Nullable<System.DateTime> DUEDTE { get; set; }
        public string PRCARE { get; set; }
        public int WKOQTY { get; set; }
        public string WKOLIN { get; set; }
        public string C_PRTNUM { get; set; }
        public decimal BOM_CNSQTY { get; set; }
        public string C_ORGCOD { get; set; }
    }
}
