//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_XCEC_ORDER_LN_BASE
    {
        public string CUST_ORDER_NO { get; set; }
        public decimal ORDER_LINE_NO { get; set; }
        public string KITS_FLAG { get; set; }
        public string PART_NO { get; set; }
        public string CUST_PART_NO { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESC_CN { get; set; }
    }
}
