//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_XCEC_INT_INV
    {
        public string WH { get; set; }
        public string PART_NO { get; set; }
        public string XCEC_PART_NO { get; set; }
        public Nullable<decimal> QTY_ONHAND { get; set; }
        public Nullable<decimal> QTY_RESERVED { get; set; }
        public Nullable<decimal> QTY_IN_RECEIVING { get; set; }
        public Nullable<decimal> QTY_IN_PICKING { get; set; }
        public Nullable<decimal> QTY_AVL { get; set; }
    }
}
