//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WILL_BILL_AUDIT
    {
        public string FROM_SYSTEM { get; set; }
        public long SHIPMENT_NO { get; set; }
        public Nullable<long> SHIPMENT_LINE_NO { get; set; }
        public string NEW_WILL_BILL_NO { get; set; }
        public string OLD_WILL_BILL_NO { get; set; }
        public System.DateTime ACTIVITY_DATE { get; set; }
    }
}
