//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHubDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_CATALOG_CUSTOMER_PART
    {
        public string SYSID { get; set; }
        public string CATALOG_NO { get; set; }
        public string CUSTOMER_PARTNO { get; set; }
        public string CUSTOMER_PARTNO_DESC { get; set; }
        public string CUSTOMER_NO { get; set; }
        public Nullable<System.DateTime> BEGIN_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
    }
}
