using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CHubDBEntity.UnmanagedModel
{
    public class V_PLABEL_BY_MOBILE_PRINT
    {
        public string VID { get; set; }
        public string NOTE { get; set; }
        public string WH_ID { get; set; }
        public string SHIP_ID { get; set; }
        public string LODNUM { get; set; }
        public string SHPSTS { get; set; }
        public string SHPSTS_DESC { get; set; }
        public Nullable<System.DateTime> STGDTE { get; set; }
        public Nullable<System.DateTime> LODDTE { get; set; }
        public string ADRNAM { get; set; }
        public string ORGCOD { get; set; }
        public string PRTNUM { get; set; }
        public Nullable<decimal> UNTQTY { get; set; }
        public string VC_CPONUM { get; set; }
        public string COUNTRY_DESC_CN { get; set; }
        public string PART_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESC_CN { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string UNIT_MEAS { get; set; }
        public Nullable<decimal> PART_HEIGHT { get; set; }
        public Nullable<decimal> PART_LENGTH { get; set; }
        public Nullable<decimal> PART_WIDTH { get; set; }
        public Nullable<decimal> PART_WEIGHT { get; set; }
        public string LWH { get; set; }
        public string CURRENT_SALES_STATUS_CODE { get; set; }
        public string PRINT_PART_NO { get; set; }
        public Nullable<decimal> MIN_ORDER_QTY { get; set; }
        public Nullable<decimal> QTY_IN_CARTON { get; set; }
        public Nullable<decimal> COPIES { get; set; }
        public string LABEL_CODE { get; set; }
        public string LABEL_DESC { get; set; }
        public string ACTIVEIND { get; set; }
        public decimal PAPER_HORIZONTAL { get; set; }
        public decimal PAPER_VERTICAL { get; set; }
        public string C01 { get; set; }
        public string C02 { get; set; }
        public string C03 { get; set; }
        public string C04 { get; set; }
        public string C05 { get; set; }
        public string C06 { get; set; }
        public string C07 { get; set; }
        public string C08 { get; set; }
        public string C09 { get; set; }
        public string C10 { get; set; }
        public string C11 { get; set; }
        public string C12 { get; set; }
        public string C13 { get; set; }
        public string C14 { get; set; }
        public Nullable<decimal> C15 { get; set; }
        public string C16 { get; set; }
        public string C17 { get; set; }
        public string C18 { get; set; }
        public string C19 { get; set; }
        public string C20 { get; set; }
        public string C21 { get; set; }
        public string C22 { get; set; }
        public string C23 { get; set; }
        public string C24 { get; set; }
        public string T01 { get; set; }
        public string T02 { get; set; }
        public string T03 { get; set; }
        public string T04 { get; set; }
        public string T05 { get; set; }
        public string T06 { get; set; }
        public string T07 { get; set; }
        public string T08 { get; set; }
        public string T09 { get; set; }
        public string T10 { get; set; }
        public string T11 { get; set; }
        public string T12 { get; set; }
        public string T13 { get; set; }
        public string T14 { get; set; }
        public string T15 { get; set; }
        public string T16 { get; set; }
        public string T17 { get; set; }
        public string T18 { get; set; }
        public string T19 { get; set; }
        public string T20 { get; set; }
        public string T21 { get; set; }
        public string T22 { get; set; }
        public string T23 { get; set; }
        public string T24 { get; set; }
        public Nullable<double> PX01 { get; set; }
        public Nullable<double> PY01 { get; set; }
        public Nullable<double> PX02 { get; set; }
        public Nullable<double> PY02 { get; set; }
        public Nullable<double> PX03 { get; set; }
        public Nullable<double> PY03 { get; set; }
        public Nullable<double> PX04 { get; set; }
        public Nullable<double> PY04 { get; set; }
        public Nullable<double> PX05 { get; set; }
        public Nullable<double> PY05 { get; set; }
        public Nullable<double> PX06 { get; set; }
        public Nullable<double> PY06 { get; set; }
        public Nullable<double> PX07 { get; set; }
        public Nullable<double> PY07 { get; set; }
        public Nullable<double> PX08 { get; set; }
        public Nullable<double> PY08 { get; set; }
        public Nullable<double> PX09 { get; set; }
        public Nullable<double> PY09 { get; set; }
        public Nullable<double> PX10 { get; set; }
        public Nullable<double> PY10 { get; set; }
        public Nullable<double> PX11 { get; set; }
        public Nullable<double> PY11 { get; set; }
        public Nullable<double> PX12 { get; set; }
        public Nullable<double> PY12 { get; set; }
        public Nullable<double> PX13 { get; set; }
        public Nullable<double> PY13 { get; set; }
        public Nullable<double> PX14 { get; set; }
        public Nullable<double> PY14 { get; set; }
        public Nullable<double> PX15 { get; set; }
        public Nullable<double> PY15 { get; set; }
        public Nullable<double> PX16 { get; set; }
        public Nullable<double> PY16 { get; set; }
        public Nullable<double> PX17 { get; set; }
        public Nullable<double> PY17 { get; set; }
        public Nullable<double> PX18 { get; set; }
        public Nullable<double> PY18 { get; set; }
        public Nullable<double> PX19 { get; set; }
        public Nullable<double> PY19 { get; set; }
        public Nullable<double> PX20 { get; set; }
        public Nullable<double> PY20 { get; set; }
        public Nullable<double> PX21 { get; set; }
        public Nullable<double> PY21 { get; set; }
        public Nullable<double> PX22 { get; set; }
        public Nullable<double> PY22 { get; set; }
        public Nullable<double> PX23 { get; set; }
        public Nullable<double> PY23 { get; set; }
        public Nullable<double> PX24 { get; set; }
        public Nullable<double> PY24 { get; set; }
        public Nullable<decimal> S01 { get; set; }
        public Nullable<decimal> S02 { get; set; }
        public Nullable<decimal> S03 { get; set; }
        public Nullable<decimal> S04 { get; set; }
        public Nullable<decimal> S05 { get; set; }
        public Nullable<decimal> S06 { get; set; }
        public Nullable<decimal> S07 { get; set; }
        public Nullable<decimal> S08 { get; set; }
        public Nullable<decimal> S09 { get; set; }
        public Nullable<decimal> S10 { get; set; }
        public Nullable<decimal> S11 { get; set; }
        public Nullable<decimal> S12 { get; set; }
        public Nullable<decimal> S13 { get; set; }
        public Nullable<decimal> S14 { get; set; }
        public Nullable<decimal> S15 { get; set; }
        public Nullable<decimal> S16 { get; set; }
        public Nullable<decimal> S17 { get; set; }
        public Nullable<decimal> S18 { get; set; }
        public Nullable<decimal> S19 { get; set; }
        public Nullable<decimal> S20 { get; set; }
        public Nullable<decimal> S21 { get; set; }
        public Nullable<decimal> S22 { get; set; }
        public Nullable<decimal> S23 { get; set; }
        public Nullable<decimal> S24 { get; set; }
        public Nullable<decimal> SIZE_2D { get; set; }
        public string LG_PARTNO { get; set; }
        public string YT_PARTNO { get; set; }
    }
}
